// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Unk3000_JDCOHPBDPED.proto

package emu.grasscutter.net.proto;

public final class Unk3000JDCOHPBDPED {
  private Unk3000JDCOHPBDPED() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Unk3000_JDCOHPBDPEDOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Unk3000_JDCOHPBDPED)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ItemParam Unk3100_HFOFIMOGDBD = 2;</code>
     */
    java.util.List<emu.grasscutter.net.proto.ItemParamOuterClass.ItemParam> 
        getUnk3100HFOFIMOGDBDList();
    /**
     * <code>repeated .ItemParam Unk3100_HFOFIMOGDBD = 2;</code>
     */
    emu.grasscutter.net.proto.ItemParamOuterClass.ItemParam getUnk3100HFOFIMOGDBD(int index);
    /**
     * <code>repeated .ItemParam Unk3100_HFOFIMOGDBD = 2;</code>
     */
    int getUnk3100HFOFIMOGDBDCount();
    /**
     * <code>repeated .ItemParam Unk3100_HFOFIMOGDBD = 2;</code>
     */
    java.util.List<? extends emu.grasscutter.net.proto.ItemParamOuterClass.ItemParamOrBuilder> 
        getUnk3100HFOFIMOGDBDOrBuilderList();
    /**
     * <code>repeated .ItemParam Unk3100_HFOFIMOGDBD = 2;</code>
     */
    emu.grasscutter.net.proto.ItemParamOuterClass.ItemParamOrBuilder getUnk3100HFOFIMOGDBDOrBuilder(
        int index);

    /**
     * <code>.Unk3000_PKHPBOIDLEA Unk3000_CNOABNNCPOL = 6;</code>
     * @return The enum numeric value on the wire for unk3000CNOABNNCPOL.
     */
    int getUnk3000CNOABNNCPOLValue();
    /**
     * <code>.Unk3000_PKHPBOIDLEA Unk3000_CNOABNNCPOL = 6;</code>
     * @return The unk3000CNOABNNCPOL.
     */
    emu.grasscutter.net.proto.Unk3000PKHPBOIDLEA.Unk3000_PKHPBOIDLEA getUnk3000CNOABNNCPOL();

    /**
     * <code>int32 retcode = 7;</code>
     * @return The retcode.
     */
    int getRetcode();

    /**
     * <code>repeated .CompoundQueueData compound_que_data_list = 1;</code>
     */
    java.util.List<emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueData> 
        getCompoundQueDataListList();
    /**
     * <code>repeated .CompoundQueueData compound_que_data_list = 1;</code>
     */
    emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueData getCompoundQueDataList(int index);
    /**
     * <code>repeated .CompoundQueueData compound_que_data_list = 1;</code>
     */
    int getCompoundQueDataListCount();
    /**
     * <code>repeated .CompoundQueueData compound_que_data_list = 1;</code>
     */
    java.util.List<? extends emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueDataOrBuilder> 
        getCompoundQueDataListOrBuilderList();
    /**
     * <code>repeated .CompoundQueueData compound_que_data_list = 1;</code>
     */
    emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueDataOrBuilder getCompoundQueDataListOrBuilder(
        int index);
  }
  /**
   * <pre>
   * CmdId: 125
   * EnetChannelId: 0
   * EnetIsReliable: true
   * </pre>
   *
   * Protobuf type {@code Unk3000_JDCOHPBDPED}
   */
  public static final class Unk3000_JDCOHPBDPED extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Unk3000_JDCOHPBDPED)
      Unk3000_JDCOHPBDPEDOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Unk3000_JDCOHPBDPED.newBuilder() to construct.
    private Unk3000_JDCOHPBDPED(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Unk3000_JDCOHPBDPED() {
      unk3100HFOFIMOGDBD_ = java.util.Collections.emptyList();
      unk3000CNOABNNCPOL_ = 0;
      compoundQueDataList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Unk3000_JDCOHPBDPED();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Unk3000_JDCOHPBDPED(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                compoundQueDataList_ = new java.util.ArrayList<emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueData>();
                mutable_bitField0_ |= 0x00000002;
              }
              compoundQueDataList_.add(
                  input.readMessage(emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueData.parser(), extensionRegistry));
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                unk3100HFOFIMOGDBD_ = new java.util.ArrayList<emu.grasscutter.net.proto.ItemParamOuterClass.ItemParam>();
                mutable_bitField0_ |= 0x00000001;
              }
              unk3100HFOFIMOGDBD_.add(
                  input.readMessage(emu.grasscutter.net.proto.ItemParamOuterClass.ItemParam.parser(), extensionRegistry));
              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              unk3000CNOABNNCPOL_ = rawValue;
              break;
            }
            case 56: {

              retcode_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          compoundQueDataList_ = java.util.Collections.unmodifiableList(compoundQueDataList_);
        }
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          unk3100HFOFIMOGDBD_ = java.util.Collections.unmodifiableList(unk3100HFOFIMOGDBD_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.internal_static_Unk3000_JDCOHPBDPED_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.internal_static_Unk3000_JDCOHPBDPED_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED.class, emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED.Builder.class);
    }

    public static final int UNK3100_HFOFIMOGDBD_FIELD_NUMBER = 2;
    private java.util.List<emu.grasscutter.net.proto.ItemParamOuterClass.ItemParam> unk3100HFOFIMOGDBD_;
    /**
     * <code>repeated .ItemParam Unk3100_HFOFIMOGDBD = 2;</code>
     */
    @java.lang.Override
    public java.util.List<emu.grasscutter.net.proto.ItemParamOuterClass.ItemParam> getUnk3100HFOFIMOGDBDList() {
      return unk3100HFOFIMOGDBD_;
    }
    /**
     * <code>repeated .ItemParam Unk3100_HFOFIMOGDBD = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends emu.grasscutter.net.proto.ItemParamOuterClass.ItemParamOrBuilder> 
        getUnk3100HFOFIMOGDBDOrBuilderList() {
      return unk3100HFOFIMOGDBD_;
    }
    /**
     * <code>repeated .ItemParam Unk3100_HFOFIMOGDBD = 2;</code>
     */
    @java.lang.Override
    public int getUnk3100HFOFIMOGDBDCount() {
      return unk3100HFOFIMOGDBD_.size();
    }
    /**
     * <code>repeated .ItemParam Unk3100_HFOFIMOGDBD = 2;</code>
     */
    @java.lang.Override
    public emu.grasscutter.net.proto.ItemParamOuterClass.ItemParam getUnk3100HFOFIMOGDBD(int index) {
      return unk3100HFOFIMOGDBD_.get(index);
    }
    /**
     * <code>repeated .ItemParam Unk3100_HFOFIMOGDBD = 2;</code>
     */
    @java.lang.Override
    public emu.grasscutter.net.proto.ItemParamOuterClass.ItemParamOrBuilder getUnk3100HFOFIMOGDBDOrBuilder(
        int index) {
      return unk3100HFOFIMOGDBD_.get(index);
    }

    public static final int UNK3000_CNOABNNCPOL_FIELD_NUMBER = 6;
    private int unk3000CNOABNNCPOL_;
    /**
     * <code>.Unk3000_PKHPBOIDLEA Unk3000_CNOABNNCPOL = 6;</code>
     * @return The enum numeric value on the wire for unk3000CNOABNNCPOL.
     */
    @java.lang.Override public int getUnk3000CNOABNNCPOLValue() {
      return unk3000CNOABNNCPOL_;
    }
    /**
     * <code>.Unk3000_PKHPBOIDLEA Unk3000_CNOABNNCPOL = 6;</code>
     * @return The unk3000CNOABNNCPOL.
     */
    @java.lang.Override public emu.grasscutter.net.proto.Unk3000PKHPBOIDLEA.Unk3000_PKHPBOIDLEA getUnk3000CNOABNNCPOL() {
      @SuppressWarnings("deprecation")
      emu.grasscutter.net.proto.Unk3000PKHPBOIDLEA.Unk3000_PKHPBOIDLEA result = emu.grasscutter.net.proto.Unk3000PKHPBOIDLEA.Unk3000_PKHPBOIDLEA.valueOf(unk3000CNOABNNCPOL_);
      return result == null ? emu.grasscutter.net.proto.Unk3000PKHPBOIDLEA.Unk3000_PKHPBOIDLEA.UNRECOGNIZED : result;
    }

    public static final int RETCODE_FIELD_NUMBER = 7;
    private int retcode_;
    /**
     * <code>int32 retcode = 7;</code>
     * @return The retcode.
     */
    @java.lang.Override
    public int getRetcode() {
      return retcode_;
    }

    public static final int COMPOUND_QUE_DATA_LIST_FIELD_NUMBER = 1;
    private java.util.List<emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueData> compoundQueDataList_;
    /**
     * <code>repeated .CompoundQueueData compound_que_data_list = 1;</code>
     */
    @java.lang.Override
    public java.util.List<emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueData> getCompoundQueDataListList() {
      return compoundQueDataList_;
    }
    /**
     * <code>repeated .CompoundQueueData compound_que_data_list = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueDataOrBuilder> 
        getCompoundQueDataListOrBuilderList() {
      return compoundQueDataList_;
    }
    /**
     * <code>repeated .CompoundQueueData compound_que_data_list = 1;</code>
     */
    @java.lang.Override
    public int getCompoundQueDataListCount() {
      return compoundQueDataList_.size();
    }
    /**
     * <code>repeated .CompoundQueueData compound_que_data_list = 1;</code>
     */
    @java.lang.Override
    public emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueData getCompoundQueDataList(int index) {
      return compoundQueDataList_.get(index);
    }
    /**
     * <code>repeated .CompoundQueueData compound_que_data_list = 1;</code>
     */
    @java.lang.Override
    public emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueDataOrBuilder getCompoundQueDataListOrBuilder(
        int index) {
      return compoundQueDataList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < compoundQueDataList_.size(); i++) {
        output.writeMessage(1, compoundQueDataList_.get(i));
      }
      for (int i = 0; i < unk3100HFOFIMOGDBD_.size(); i++) {
        output.writeMessage(2, unk3100HFOFIMOGDBD_.get(i));
      }
      if (unk3000CNOABNNCPOL_ != emu.grasscutter.net.proto.Unk3000PKHPBOIDLEA.Unk3000_PKHPBOIDLEA.Unk3000_PKHPBOIDLEA_Unk3000_KANMGBLJEHC.getNumber()) {
        output.writeEnum(6, unk3000CNOABNNCPOL_);
      }
      if (retcode_ != 0) {
        output.writeInt32(7, retcode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < compoundQueDataList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, compoundQueDataList_.get(i));
      }
      for (int i = 0; i < unk3100HFOFIMOGDBD_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, unk3100HFOFIMOGDBD_.get(i));
      }
      if (unk3000CNOABNNCPOL_ != emu.grasscutter.net.proto.Unk3000PKHPBOIDLEA.Unk3000_PKHPBOIDLEA.Unk3000_PKHPBOIDLEA_Unk3000_KANMGBLJEHC.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, unk3000CNOABNNCPOL_);
      }
      if (retcode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, retcode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED)) {
        return super.equals(obj);
      }
      emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED other = (emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED) obj;

      if (!getUnk3100HFOFIMOGDBDList()
          .equals(other.getUnk3100HFOFIMOGDBDList())) return false;
      if (unk3000CNOABNNCPOL_ != other.unk3000CNOABNNCPOL_) return false;
      if (getRetcode()
          != other.getRetcode()) return false;
      if (!getCompoundQueDataListList()
          .equals(other.getCompoundQueDataListList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getUnk3100HFOFIMOGDBDCount() > 0) {
        hash = (37 * hash) + UNK3100_HFOFIMOGDBD_FIELD_NUMBER;
        hash = (53 * hash) + getUnk3100HFOFIMOGDBDList().hashCode();
      }
      hash = (37 * hash) + UNK3000_CNOABNNCPOL_FIELD_NUMBER;
      hash = (53 * hash) + unk3000CNOABNNCPOL_;
      hash = (37 * hash) + RETCODE_FIELD_NUMBER;
      hash = (53 * hash) + getRetcode();
      if (getCompoundQueDataListCount() > 0) {
        hash = (37 * hash) + COMPOUND_QUE_DATA_LIST_FIELD_NUMBER;
        hash = (53 * hash) + getCompoundQueDataListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * CmdId: 125
     * EnetChannelId: 0
     * EnetIsReliable: true
     * </pre>
     *
     * Protobuf type {@code Unk3000_JDCOHPBDPED}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Unk3000_JDCOHPBDPED)
        emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPEDOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.internal_static_Unk3000_JDCOHPBDPED_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.internal_static_Unk3000_JDCOHPBDPED_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED.class, emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED.Builder.class);
      }

      // Construct using emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getUnk3100HFOFIMOGDBDFieldBuilder();
          getCompoundQueDataListFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (unk3100HFOFIMOGDBDBuilder_ == null) {
          unk3100HFOFIMOGDBD_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          unk3100HFOFIMOGDBDBuilder_.clear();
        }
        unk3000CNOABNNCPOL_ = 0;

        retcode_ = 0;

        if (compoundQueDataListBuilder_ == null) {
          compoundQueDataList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          compoundQueDataListBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.internal_static_Unk3000_JDCOHPBDPED_descriptor;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED getDefaultInstanceForType() {
        return emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED.getDefaultInstance();
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED build() {
        emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED buildPartial() {
        emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED result = new emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED(this);
        int from_bitField0_ = bitField0_;
        if (unk3100HFOFIMOGDBDBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            unk3100HFOFIMOGDBD_ = java.util.Collections.unmodifiableList(unk3100HFOFIMOGDBD_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.unk3100HFOFIMOGDBD_ = unk3100HFOFIMOGDBD_;
        } else {
          result.unk3100HFOFIMOGDBD_ = unk3100HFOFIMOGDBDBuilder_.build();
        }
        result.unk3000CNOABNNCPOL_ = unk3000CNOABNNCPOL_;
        result.retcode_ = retcode_;
        if (compoundQueDataListBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            compoundQueDataList_ = java.util.Collections.unmodifiableList(compoundQueDataList_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.compoundQueDataList_ = compoundQueDataList_;
        } else {
          result.compoundQueDataList_ = compoundQueDataListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED) {
          return mergeFrom((emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED other) {
        if (other == emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED.getDefaultInstance()) return this;
        if (unk3100HFOFIMOGDBDBuilder_ == null) {
          if (!other.unk3100HFOFIMOGDBD_.isEmpty()) {
            if (unk3100HFOFIMOGDBD_.isEmpty()) {
              unk3100HFOFIMOGDBD_ = other.unk3100HFOFIMOGDBD_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureUnk3100HFOFIMOGDBDIsMutable();
              unk3100HFOFIMOGDBD_.addAll(other.unk3100HFOFIMOGDBD_);
            }
            onChanged();
          }
        } else {
          if (!other.unk3100HFOFIMOGDBD_.isEmpty()) {
            if (unk3100HFOFIMOGDBDBuilder_.isEmpty()) {
              unk3100HFOFIMOGDBDBuilder_.dispose();
              unk3100HFOFIMOGDBDBuilder_ = null;
              unk3100HFOFIMOGDBD_ = other.unk3100HFOFIMOGDBD_;
              bitField0_ = (bitField0_ & ~0x00000001);
              unk3100HFOFIMOGDBDBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getUnk3100HFOFIMOGDBDFieldBuilder() : null;
            } else {
              unk3100HFOFIMOGDBDBuilder_.addAllMessages(other.unk3100HFOFIMOGDBD_);
            }
          }
        }
        if (other.unk3000CNOABNNCPOL_ != 0) {
          setUnk3000CNOABNNCPOLValue(other.getUnk3000CNOABNNCPOLValue());
        }
        if (other.getRetcode() != 0) {
          setRetcode(other.getRetcode());
        }
        if (compoundQueDataListBuilder_ == null) {
          if (!other.compoundQueDataList_.isEmpty()) {
            if (compoundQueDataList_.isEmpty()) {
              compoundQueDataList_ = other.compoundQueDataList_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureCompoundQueDataListIsMutable();
              compoundQueDataList_.addAll(other.compoundQueDataList_);
            }
            onChanged();
          }
        } else {
          if (!other.compoundQueDataList_.isEmpty()) {
            if (compoundQueDataListBuilder_.isEmpty()) {
              compoundQueDataListBuilder_.dispose();
              compoundQueDataListBuilder_ = null;
              compoundQueDataList_ = other.compoundQueDataList_;
              bitField0_ = (bitField0_ & ~0x00000002);
              compoundQueDataListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCompoundQueDataListFieldBuilder() : null;
            } else {
              compoundQueDataListBuilder_.addAllMessages(other.compoundQueDataList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<emu.grasscutter.net.proto.ItemParamOuterClass.ItemParam> unk3100HFOFIMOGDBD_ =
        java.util.Collections.emptyList();
      private void ensureUnk3100HFOFIMOGDBDIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          unk3100HFOFIMOGDBD_ = new java.util.ArrayList<emu.grasscutter.net.proto.ItemParamOuterClass.ItemParam>(unk3100HFOFIMOGDBD_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          emu.grasscutter.net.proto.ItemParamOuterClass.ItemParam, emu.grasscutter.net.proto.ItemParamOuterClass.ItemParam.Builder, emu.grasscutter.net.proto.ItemParamOuterClass.ItemParamOrBuilder> unk3100HFOFIMOGDBDBuilder_;

      /**
       * <code>repeated .ItemParam Unk3100_HFOFIMOGDBD = 2;</code>
       */
      public java.util.List<emu.grasscutter.net.proto.ItemParamOuterClass.ItemParam> getUnk3100HFOFIMOGDBDList() {
        if (unk3100HFOFIMOGDBDBuilder_ == null) {
          return java.util.Collections.unmodifiableList(unk3100HFOFIMOGDBD_);
        } else {
          return unk3100HFOFIMOGDBDBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ItemParam Unk3100_HFOFIMOGDBD = 2;</code>
       */
      public int getUnk3100HFOFIMOGDBDCount() {
        if (unk3100HFOFIMOGDBDBuilder_ == null) {
          return unk3100HFOFIMOGDBD_.size();
        } else {
          return unk3100HFOFIMOGDBDBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ItemParam Unk3100_HFOFIMOGDBD = 2;</code>
       */
      public emu.grasscutter.net.proto.ItemParamOuterClass.ItemParam getUnk3100HFOFIMOGDBD(int index) {
        if (unk3100HFOFIMOGDBDBuilder_ == null) {
          return unk3100HFOFIMOGDBD_.get(index);
        } else {
          return unk3100HFOFIMOGDBDBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ItemParam Unk3100_HFOFIMOGDBD = 2;</code>
       */
      public Builder setUnk3100HFOFIMOGDBD(
          int index, emu.grasscutter.net.proto.ItemParamOuterClass.ItemParam value) {
        if (unk3100HFOFIMOGDBDBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUnk3100HFOFIMOGDBDIsMutable();
          unk3100HFOFIMOGDBD_.set(index, value);
          onChanged();
        } else {
          unk3100HFOFIMOGDBDBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ItemParam Unk3100_HFOFIMOGDBD = 2;</code>
       */
      public Builder setUnk3100HFOFIMOGDBD(
          int index, emu.grasscutter.net.proto.ItemParamOuterClass.ItemParam.Builder builderForValue) {
        if (unk3100HFOFIMOGDBDBuilder_ == null) {
          ensureUnk3100HFOFIMOGDBDIsMutable();
          unk3100HFOFIMOGDBD_.set(index, builderForValue.build());
          onChanged();
        } else {
          unk3100HFOFIMOGDBDBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ItemParam Unk3100_HFOFIMOGDBD = 2;</code>
       */
      public Builder addUnk3100HFOFIMOGDBD(emu.grasscutter.net.proto.ItemParamOuterClass.ItemParam value) {
        if (unk3100HFOFIMOGDBDBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUnk3100HFOFIMOGDBDIsMutable();
          unk3100HFOFIMOGDBD_.add(value);
          onChanged();
        } else {
          unk3100HFOFIMOGDBDBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ItemParam Unk3100_HFOFIMOGDBD = 2;</code>
       */
      public Builder addUnk3100HFOFIMOGDBD(
          int index, emu.grasscutter.net.proto.ItemParamOuterClass.ItemParam value) {
        if (unk3100HFOFIMOGDBDBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUnk3100HFOFIMOGDBDIsMutable();
          unk3100HFOFIMOGDBD_.add(index, value);
          onChanged();
        } else {
          unk3100HFOFIMOGDBDBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ItemParam Unk3100_HFOFIMOGDBD = 2;</code>
       */
      public Builder addUnk3100HFOFIMOGDBD(
          emu.grasscutter.net.proto.ItemParamOuterClass.ItemParam.Builder builderForValue) {
        if (unk3100HFOFIMOGDBDBuilder_ == null) {
          ensureUnk3100HFOFIMOGDBDIsMutable();
          unk3100HFOFIMOGDBD_.add(builderForValue.build());
          onChanged();
        } else {
          unk3100HFOFIMOGDBDBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ItemParam Unk3100_HFOFIMOGDBD = 2;</code>
       */
      public Builder addUnk3100HFOFIMOGDBD(
          int index, emu.grasscutter.net.proto.ItemParamOuterClass.ItemParam.Builder builderForValue) {
        if (unk3100HFOFIMOGDBDBuilder_ == null) {
          ensureUnk3100HFOFIMOGDBDIsMutable();
          unk3100HFOFIMOGDBD_.add(index, builderForValue.build());
          onChanged();
        } else {
          unk3100HFOFIMOGDBDBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ItemParam Unk3100_HFOFIMOGDBD = 2;</code>
       */
      public Builder addAllUnk3100HFOFIMOGDBD(
          java.lang.Iterable<? extends emu.grasscutter.net.proto.ItemParamOuterClass.ItemParam> values) {
        if (unk3100HFOFIMOGDBDBuilder_ == null) {
          ensureUnk3100HFOFIMOGDBDIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, unk3100HFOFIMOGDBD_);
          onChanged();
        } else {
          unk3100HFOFIMOGDBDBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ItemParam Unk3100_HFOFIMOGDBD = 2;</code>
       */
      public Builder clearUnk3100HFOFIMOGDBD() {
        if (unk3100HFOFIMOGDBDBuilder_ == null) {
          unk3100HFOFIMOGDBD_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          unk3100HFOFIMOGDBDBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ItemParam Unk3100_HFOFIMOGDBD = 2;</code>
       */
      public Builder removeUnk3100HFOFIMOGDBD(int index) {
        if (unk3100HFOFIMOGDBDBuilder_ == null) {
          ensureUnk3100HFOFIMOGDBDIsMutable();
          unk3100HFOFIMOGDBD_.remove(index);
          onChanged();
        } else {
          unk3100HFOFIMOGDBDBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ItemParam Unk3100_HFOFIMOGDBD = 2;</code>
       */
      public emu.grasscutter.net.proto.ItemParamOuterClass.ItemParam.Builder getUnk3100HFOFIMOGDBDBuilder(
          int index) {
        return getUnk3100HFOFIMOGDBDFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ItemParam Unk3100_HFOFIMOGDBD = 2;</code>
       */
      public emu.grasscutter.net.proto.ItemParamOuterClass.ItemParamOrBuilder getUnk3100HFOFIMOGDBDOrBuilder(
          int index) {
        if (unk3100HFOFIMOGDBDBuilder_ == null) {
          return unk3100HFOFIMOGDBD_.get(index);  } else {
          return unk3100HFOFIMOGDBDBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ItemParam Unk3100_HFOFIMOGDBD = 2;</code>
       */
      public java.util.List<? extends emu.grasscutter.net.proto.ItemParamOuterClass.ItemParamOrBuilder> 
           getUnk3100HFOFIMOGDBDOrBuilderList() {
        if (unk3100HFOFIMOGDBDBuilder_ != null) {
          return unk3100HFOFIMOGDBDBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(unk3100HFOFIMOGDBD_);
        }
      }
      /**
       * <code>repeated .ItemParam Unk3100_HFOFIMOGDBD = 2;</code>
       */
      public emu.grasscutter.net.proto.ItemParamOuterClass.ItemParam.Builder addUnk3100HFOFIMOGDBDBuilder() {
        return getUnk3100HFOFIMOGDBDFieldBuilder().addBuilder(
            emu.grasscutter.net.proto.ItemParamOuterClass.ItemParam.getDefaultInstance());
      }
      /**
       * <code>repeated .ItemParam Unk3100_HFOFIMOGDBD = 2;</code>
       */
      public emu.grasscutter.net.proto.ItemParamOuterClass.ItemParam.Builder addUnk3100HFOFIMOGDBDBuilder(
          int index) {
        return getUnk3100HFOFIMOGDBDFieldBuilder().addBuilder(
            index, emu.grasscutter.net.proto.ItemParamOuterClass.ItemParam.getDefaultInstance());
      }
      /**
       * <code>repeated .ItemParam Unk3100_HFOFIMOGDBD = 2;</code>
       */
      public java.util.List<emu.grasscutter.net.proto.ItemParamOuterClass.ItemParam.Builder> 
           getUnk3100HFOFIMOGDBDBuilderList() {
        return getUnk3100HFOFIMOGDBDFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          emu.grasscutter.net.proto.ItemParamOuterClass.ItemParam, emu.grasscutter.net.proto.ItemParamOuterClass.ItemParam.Builder, emu.grasscutter.net.proto.ItemParamOuterClass.ItemParamOrBuilder> 
          getUnk3100HFOFIMOGDBDFieldBuilder() {
        if (unk3100HFOFIMOGDBDBuilder_ == null) {
          unk3100HFOFIMOGDBDBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              emu.grasscutter.net.proto.ItemParamOuterClass.ItemParam, emu.grasscutter.net.proto.ItemParamOuterClass.ItemParam.Builder, emu.grasscutter.net.proto.ItemParamOuterClass.ItemParamOrBuilder>(
                  unk3100HFOFIMOGDBD_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          unk3100HFOFIMOGDBD_ = null;
        }
        return unk3100HFOFIMOGDBDBuilder_;
      }

      private int unk3000CNOABNNCPOL_ = 0;
      /**
       * <code>.Unk3000_PKHPBOIDLEA Unk3000_CNOABNNCPOL = 6;</code>
       * @return The enum numeric value on the wire for unk3000CNOABNNCPOL.
       */
      @java.lang.Override public int getUnk3000CNOABNNCPOLValue() {
        return unk3000CNOABNNCPOL_;
      }
      /**
       * <code>.Unk3000_PKHPBOIDLEA Unk3000_CNOABNNCPOL = 6;</code>
       * @param value The enum numeric value on the wire for unk3000CNOABNNCPOL to set.
       * @return This builder for chaining.
       */
      public Builder setUnk3000CNOABNNCPOLValue(int value) {
        
        unk3000CNOABNNCPOL_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Unk3000_PKHPBOIDLEA Unk3000_CNOABNNCPOL = 6;</code>
       * @return The unk3000CNOABNNCPOL.
       */
      @java.lang.Override
      public emu.grasscutter.net.proto.Unk3000PKHPBOIDLEA.Unk3000_PKHPBOIDLEA getUnk3000CNOABNNCPOL() {
        @SuppressWarnings("deprecation")
        emu.grasscutter.net.proto.Unk3000PKHPBOIDLEA.Unk3000_PKHPBOIDLEA result = emu.grasscutter.net.proto.Unk3000PKHPBOIDLEA.Unk3000_PKHPBOIDLEA.valueOf(unk3000CNOABNNCPOL_);
        return result == null ? emu.grasscutter.net.proto.Unk3000PKHPBOIDLEA.Unk3000_PKHPBOIDLEA.UNRECOGNIZED : result;
      }
      /**
       * <code>.Unk3000_PKHPBOIDLEA Unk3000_CNOABNNCPOL = 6;</code>
       * @param value The unk3000CNOABNNCPOL to set.
       * @return This builder for chaining.
       */
      public Builder setUnk3000CNOABNNCPOL(emu.grasscutter.net.proto.Unk3000PKHPBOIDLEA.Unk3000_PKHPBOIDLEA value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        unk3000CNOABNNCPOL_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Unk3000_PKHPBOIDLEA Unk3000_CNOABNNCPOL = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnk3000CNOABNNCPOL() {
        
        unk3000CNOABNNCPOL_ = 0;
        onChanged();
        return this;
      }

      private int retcode_ ;
      /**
       * <code>int32 retcode = 7;</code>
       * @return The retcode.
       */
      @java.lang.Override
      public int getRetcode() {
        return retcode_;
      }
      /**
       * <code>int32 retcode = 7;</code>
       * @param value The retcode to set.
       * @return This builder for chaining.
       */
      public Builder setRetcode(int value) {
        
        retcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 retcode = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearRetcode() {
        
        retcode_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueData> compoundQueDataList_ =
        java.util.Collections.emptyList();
      private void ensureCompoundQueDataListIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          compoundQueDataList_ = new java.util.ArrayList<emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueData>(compoundQueDataList_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueData, emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueData.Builder, emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueDataOrBuilder> compoundQueDataListBuilder_;

      /**
       * <code>repeated .CompoundQueueData compound_que_data_list = 1;</code>
       */
      public java.util.List<emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueData> getCompoundQueDataListList() {
        if (compoundQueDataListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(compoundQueDataList_);
        } else {
          return compoundQueDataListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .CompoundQueueData compound_que_data_list = 1;</code>
       */
      public int getCompoundQueDataListCount() {
        if (compoundQueDataListBuilder_ == null) {
          return compoundQueDataList_.size();
        } else {
          return compoundQueDataListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .CompoundQueueData compound_que_data_list = 1;</code>
       */
      public emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueData getCompoundQueDataList(int index) {
        if (compoundQueDataListBuilder_ == null) {
          return compoundQueDataList_.get(index);
        } else {
          return compoundQueDataListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .CompoundQueueData compound_que_data_list = 1;</code>
       */
      public Builder setCompoundQueDataList(
          int index, emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueData value) {
        if (compoundQueDataListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCompoundQueDataListIsMutable();
          compoundQueDataList_.set(index, value);
          onChanged();
        } else {
          compoundQueDataListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CompoundQueueData compound_que_data_list = 1;</code>
       */
      public Builder setCompoundQueDataList(
          int index, emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueData.Builder builderForValue) {
        if (compoundQueDataListBuilder_ == null) {
          ensureCompoundQueDataListIsMutable();
          compoundQueDataList_.set(index, builderForValue.build());
          onChanged();
        } else {
          compoundQueDataListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CompoundQueueData compound_que_data_list = 1;</code>
       */
      public Builder addCompoundQueDataList(emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueData value) {
        if (compoundQueDataListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCompoundQueDataListIsMutable();
          compoundQueDataList_.add(value);
          onChanged();
        } else {
          compoundQueDataListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .CompoundQueueData compound_que_data_list = 1;</code>
       */
      public Builder addCompoundQueDataList(
          int index, emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueData value) {
        if (compoundQueDataListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCompoundQueDataListIsMutable();
          compoundQueDataList_.add(index, value);
          onChanged();
        } else {
          compoundQueDataListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CompoundQueueData compound_que_data_list = 1;</code>
       */
      public Builder addCompoundQueDataList(
          emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueData.Builder builderForValue) {
        if (compoundQueDataListBuilder_ == null) {
          ensureCompoundQueDataListIsMutable();
          compoundQueDataList_.add(builderForValue.build());
          onChanged();
        } else {
          compoundQueDataListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CompoundQueueData compound_que_data_list = 1;</code>
       */
      public Builder addCompoundQueDataList(
          int index, emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueData.Builder builderForValue) {
        if (compoundQueDataListBuilder_ == null) {
          ensureCompoundQueDataListIsMutable();
          compoundQueDataList_.add(index, builderForValue.build());
          onChanged();
        } else {
          compoundQueDataListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CompoundQueueData compound_que_data_list = 1;</code>
       */
      public Builder addAllCompoundQueDataList(
          java.lang.Iterable<? extends emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueData> values) {
        if (compoundQueDataListBuilder_ == null) {
          ensureCompoundQueDataListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, compoundQueDataList_);
          onChanged();
        } else {
          compoundQueDataListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .CompoundQueueData compound_que_data_list = 1;</code>
       */
      public Builder clearCompoundQueDataList() {
        if (compoundQueDataListBuilder_ == null) {
          compoundQueDataList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          compoundQueDataListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .CompoundQueueData compound_que_data_list = 1;</code>
       */
      public Builder removeCompoundQueDataList(int index) {
        if (compoundQueDataListBuilder_ == null) {
          ensureCompoundQueDataListIsMutable();
          compoundQueDataList_.remove(index);
          onChanged();
        } else {
          compoundQueDataListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .CompoundQueueData compound_que_data_list = 1;</code>
       */
      public emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueData.Builder getCompoundQueDataListBuilder(
          int index) {
        return getCompoundQueDataListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .CompoundQueueData compound_que_data_list = 1;</code>
       */
      public emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueDataOrBuilder getCompoundQueDataListOrBuilder(
          int index) {
        if (compoundQueDataListBuilder_ == null) {
          return compoundQueDataList_.get(index);  } else {
          return compoundQueDataListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .CompoundQueueData compound_que_data_list = 1;</code>
       */
      public java.util.List<? extends emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueDataOrBuilder> 
           getCompoundQueDataListOrBuilderList() {
        if (compoundQueDataListBuilder_ != null) {
          return compoundQueDataListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(compoundQueDataList_);
        }
      }
      /**
       * <code>repeated .CompoundQueueData compound_que_data_list = 1;</code>
       */
      public emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueData.Builder addCompoundQueDataListBuilder() {
        return getCompoundQueDataListFieldBuilder().addBuilder(
            emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueData.getDefaultInstance());
      }
      /**
       * <code>repeated .CompoundQueueData compound_que_data_list = 1;</code>
       */
      public emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueData.Builder addCompoundQueDataListBuilder(
          int index) {
        return getCompoundQueDataListFieldBuilder().addBuilder(
            index, emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueData.getDefaultInstance());
      }
      /**
       * <code>repeated .CompoundQueueData compound_que_data_list = 1;</code>
       */
      public java.util.List<emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueData.Builder> 
           getCompoundQueDataListBuilderList() {
        return getCompoundQueDataListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueData, emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueData.Builder, emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueDataOrBuilder> 
          getCompoundQueDataListFieldBuilder() {
        if (compoundQueDataListBuilder_ == null) {
          compoundQueDataListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueData, emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueData.Builder, emu.grasscutter.net.proto.CompoundQueueDataOuterClass.CompoundQueueDataOrBuilder>(
                  compoundQueDataList_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          compoundQueDataList_ = null;
        }
        return compoundQueDataListBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Unk3000_JDCOHPBDPED)
    }

    // @@protoc_insertion_point(class_scope:Unk3000_JDCOHPBDPED)
    private static final emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED();
    }

    public static emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Unk3000_JDCOHPBDPED>
        PARSER = new com.google.protobuf.AbstractParser<Unk3000_JDCOHPBDPED>() {
      @java.lang.Override
      public Unk3000_JDCOHPBDPED parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Unk3000_JDCOHPBDPED(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Unk3000_JDCOHPBDPED> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Unk3000_JDCOHPBDPED> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public emu.grasscutter.net.proto.Unk3000JDCOHPBDPED.Unk3000_JDCOHPBDPED getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Unk3000_JDCOHPBDPED_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Unk3000_JDCOHPBDPED_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031Unk3000_JDCOHPBDPED.proto\032\027CompoundQue" +
      "ueData.proto\032\017ItemParam.proto\032\031Unk3000_P" +
      "KHPBOIDLEA.proto\"\266\001\n\023Unk3000_JDCOHPBDPED" +
      "\022\'\n\023Unk3100_HFOFIMOGDBD\030\002 \003(\0132\n.ItemPara" +
      "m\0221\n\023Unk3000_CNOABNNCPOL\030\006 \001(\0162\024.Unk3000" +
      "_PKHPBOIDLEA\022\017\n\007retcode\030\007 \001(\005\0222\n\026compoun" +
      "d_que_data_list\030\001 \003(\0132\022.CompoundQueueDat" +
      "aB\033\n\031emu.grasscutter.net.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          emu.grasscutter.net.proto.CompoundQueueDataOuterClass.getDescriptor(),
          emu.grasscutter.net.proto.ItemParamOuterClass.getDescriptor(),
          emu.grasscutter.net.proto.Unk3000PKHPBOIDLEA.getDescriptor(),
        });
    internal_static_Unk3000_JDCOHPBDPED_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Unk3000_JDCOHPBDPED_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Unk3000_JDCOHPBDPED_descriptor,
        new java.lang.String[] { "Unk3100HFOFIMOGDBD", "Unk3000CNOABNNCPOL", "Retcode", "CompoundQueDataList", });
    emu.grasscutter.net.proto.CompoundQueueDataOuterClass.getDescriptor();
    emu.grasscutter.net.proto.ItemParamOuterClass.getDescriptor();
    emu.grasscutter.net.proto.Unk3000PKHPBOIDLEA.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
