// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Unk3100_FGDECIHNIJG.proto

package emu.grasscutter.net.proto;

public final class Unk3100FGDECIHNIJG {
  private Unk3100FGDECIHNIJG() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Unk3100_FGDECIHNIJGOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Unk3100_FGDECIHNIJG)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Unk3100_MCIBDBBEKEK Unk3100_IMPDKHPHALG = 2;</code>
     */
    java.util.List<emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEK> 
        getUnk3100IMPDKHPHALGList();
    /**
     * <code>repeated .Unk3100_MCIBDBBEKEK Unk3100_IMPDKHPHALG = 2;</code>
     */
    emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEK getUnk3100IMPDKHPHALG(int index);
    /**
     * <code>repeated .Unk3100_MCIBDBBEKEK Unk3100_IMPDKHPHALG = 2;</code>
     */
    int getUnk3100IMPDKHPHALGCount();
    /**
     * <code>repeated .Unk3100_MCIBDBBEKEK Unk3100_IMPDKHPHALG = 2;</code>
     */
    java.util.List<? extends emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEKOrBuilder> 
        getUnk3100IMPDKHPHALGOrBuilderList();
    /**
     * <code>repeated .Unk3100_MCIBDBBEKEK Unk3100_IMPDKHPHALG = 2;</code>
     */
    emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEKOrBuilder getUnk3100IMPDKHPHALGOrBuilder(
        int index);
  }
  /**
   * <pre>
   * CmdId: 6395
   * EnetChannelId: 0
   * EnetIsReliable: true
   * </pre>
   *
   * Protobuf type {@code Unk3100_FGDECIHNIJG}
   */
  public static final class Unk3100_FGDECIHNIJG extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Unk3100_FGDECIHNIJG)
      Unk3100_FGDECIHNIJGOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Unk3100_FGDECIHNIJG.newBuilder() to construct.
    private Unk3100_FGDECIHNIJG(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Unk3100_FGDECIHNIJG() {
      unk3100IMPDKHPHALG_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Unk3100_FGDECIHNIJG();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Unk3100_FGDECIHNIJG(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                unk3100IMPDKHPHALG_ = new java.util.ArrayList<emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEK>();
                mutable_bitField0_ |= 0x00000001;
              }
              unk3100IMPDKHPHALG_.add(
                  input.readMessage(emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEK.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          unk3100IMPDKHPHALG_ = java.util.Collections.unmodifiableList(unk3100IMPDKHPHALG_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.internal_static_Unk3100_FGDECIHNIJG_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.internal_static_Unk3100_FGDECIHNIJG_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG.class, emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG.Builder.class);
    }

    public static final int UNK3100_IMPDKHPHALG_FIELD_NUMBER = 2;
    private java.util.List<emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEK> unk3100IMPDKHPHALG_;
    /**
     * <code>repeated .Unk3100_MCIBDBBEKEK Unk3100_IMPDKHPHALG = 2;</code>
     */
    @java.lang.Override
    public java.util.List<emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEK> getUnk3100IMPDKHPHALGList() {
      return unk3100IMPDKHPHALG_;
    }
    /**
     * <code>repeated .Unk3100_MCIBDBBEKEK Unk3100_IMPDKHPHALG = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEKOrBuilder> 
        getUnk3100IMPDKHPHALGOrBuilderList() {
      return unk3100IMPDKHPHALG_;
    }
    /**
     * <code>repeated .Unk3100_MCIBDBBEKEK Unk3100_IMPDKHPHALG = 2;</code>
     */
    @java.lang.Override
    public int getUnk3100IMPDKHPHALGCount() {
      return unk3100IMPDKHPHALG_.size();
    }
    /**
     * <code>repeated .Unk3100_MCIBDBBEKEK Unk3100_IMPDKHPHALG = 2;</code>
     */
    @java.lang.Override
    public emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEK getUnk3100IMPDKHPHALG(int index) {
      return unk3100IMPDKHPHALG_.get(index);
    }
    /**
     * <code>repeated .Unk3100_MCIBDBBEKEK Unk3100_IMPDKHPHALG = 2;</code>
     */
    @java.lang.Override
    public emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEKOrBuilder getUnk3100IMPDKHPHALGOrBuilder(
        int index) {
      return unk3100IMPDKHPHALG_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < unk3100IMPDKHPHALG_.size(); i++) {
        output.writeMessage(2, unk3100IMPDKHPHALG_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < unk3100IMPDKHPHALG_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, unk3100IMPDKHPHALG_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG)) {
        return super.equals(obj);
      }
      emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG other = (emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG) obj;

      if (!getUnk3100IMPDKHPHALGList()
          .equals(other.getUnk3100IMPDKHPHALGList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getUnk3100IMPDKHPHALGCount() > 0) {
        hash = (37 * hash) + UNK3100_IMPDKHPHALG_FIELD_NUMBER;
        hash = (53 * hash) + getUnk3100IMPDKHPHALGList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * CmdId: 6395
     * EnetChannelId: 0
     * EnetIsReliable: true
     * </pre>
     *
     * Protobuf type {@code Unk3100_FGDECIHNIJG}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Unk3100_FGDECIHNIJG)
        emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJGOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.internal_static_Unk3100_FGDECIHNIJG_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.internal_static_Unk3100_FGDECIHNIJG_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG.class, emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG.Builder.class);
      }

      // Construct using emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getUnk3100IMPDKHPHALGFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (unk3100IMPDKHPHALGBuilder_ == null) {
          unk3100IMPDKHPHALG_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          unk3100IMPDKHPHALGBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.internal_static_Unk3100_FGDECIHNIJG_descriptor;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG getDefaultInstanceForType() {
        return emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG.getDefaultInstance();
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG build() {
        emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG buildPartial() {
        emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG result = new emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG(this);
        int from_bitField0_ = bitField0_;
        if (unk3100IMPDKHPHALGBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            unk3100IMPDKHPHALG_ = java.util.Collections.unmodifiableList(unk3100IMPDKHPHALG_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.unk3100IMPDKHPHALG_ = unk3100IMPDKHPHALG_;
        } else {
          result.unk3100IMPDKHPHALG_ = unk3100IMPDKHPHALGBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG) {
          return mergeFrom((emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG other) {
        if (other == emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG.getDefaultInstance()) return this;
        if (unk3100IMPDKHPHALGBuilder_ == null) {
          if (!other.unk3100IMPDKHPHALG_.isEmpty()) {
            if (unk3100IMPDKHPHALG_.isEmpty()) {
              unk3100IMPDKHPHALG_ = other.unk3100IMPDKHPHALG_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureUnk3100IMPDKHPHALGIsMutable();
              unk3100IMPDKHPHALG_.addAll(other.unk3100IMPDKHPHALG_);
            }
            onChanged();
          }
        } else {
          if (!other.unk3100IMPDKHPHALG_.isEmpty()) {
            if (unk3100IMPDKHPHALGBuilder_.isEmpty()) {
              unk3100IMPDKHPHALGBuilder_.dispose();
              unk3100IMPDKHPHALGBuilder_ = null;
              unk3100IMPDKHPHALG_ = other.unk3100IMPDKHPHALG_;
              bitField0_ = (bitField0_ & ~0x00000001);
              unk3100IMPDKHPHALGBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getUnk3100IMPDKHPHALGFieldBuilder() : null;
            } else {
              unk3100IMPDKHPHALGBuilder_.addAllMessages(other.unk3100IMPDKHPHALG_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEK> unk3100IMPDKHPHALG_ =
        java.util.Collections.emptyList();
      private void ensureUnk3100IMPDKHPHALGIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          unk3100IMPDKHPHALG_ = new java.util.ArrayList<emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEK>(unk3100IMPDKHPHALG_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEK, emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEK.Builder, emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEKOrBuilder> unk3100IMPDKHPHALGBuilder_;

      /**
       * <code>repeated .Unk3100_MCIBDBBEKEK Unk3100_IMPDKHPHALG = 2;</code>
       */
      public java.util.List<emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEK> getUnk3100IMPDKHPHALGList() {
        if (unk3100IMPDKHPHALGBuilder_ == null) {
          return java.util.Collections.unmodifiableList(unk3100IMPDKHPHALG_);
        } else {
          return unk3100IMPDKHPHALGBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Unk3100_MCIBDBBEKEK Unk3100_IMPDKHPHALG = 2;</code>
       */
      public int getUnk3100IMPDKHPHALGCount() {
        if (unk3100IMPDKHPHALGBuilder_ == null) {
          return unk3100IMPDKHPHALG_.size();
        } else {
          return unk3100IMPDKHPHALGBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Unk3100_MCIBDBBEKEK Unk3100_IMPDKHPHALG = 2;</code>
       */
      public emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEK getUnk3100IMPDKHPHALG(int index) {
        if (unk3100IMPDKHPHALGBuilder_ == null) {
          return unk3100IMPDKHPHALG_.get(index);
        } else {
          return unk3100IMPDKHPHALGBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Unk3100_MCIBDBBEKEK Unk3100_IMPDKHPHALG = 2;</code>
       */
      public Builder setUnk3100IMPDKHPHALG(
          int index, emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEK value) {
        if (unk3100IMPDKHPHALGBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUnk3100IMPDKHPHALGIsMutable();
          unk3100IMPDKHPHALG_.set(index, value);
          onChanged();
        } else {
          unk3100IMPDKHPHALGBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Unk3100_MCIBDBBEKEK Unk3100_IMPDKHPHALG = 2;</code>
       */
      public Builder setUnk3100IMPDKHPHALG(
          int index, emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEK.Builder builderForValue) {
        if (unk3100IMPDKHPHALGBuilder_ == null) {
          ensureUnk3100IMPDKHPHALGIsMutable();
          unk3100IMPDKHPHALG_.set(index, builderForValue.build());
          onChanged();
        } else {
          unk3100IMPDKHPHALGBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Unk3100_MCIBDBBEKEK Unk3100_IMPDKHPHALG = 2;</code>
       */
      public Builder addUnk3100IMPDKHPHALG(emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEK value) {
        if (unk3100IMPDKHPHALGBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUnk3100IMPDKHPHALGIsMutable();
          unk3100IMPDKHPHALG_.add(value);
          onChanged();
        } else {
          unk3100IMPDKHPHALGBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Unk3100_MCIBDBBEKEK Unk3100_IMPDKHPHALG = 2;</code>
       */
      public Builder addUnk3100IMPDKHPHALG(
          int index, emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEK value) {
        if (unk3100IMPDKHPHALGBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUnk3100IMPDKHPHALGIsMutable();
          unk3100IMPDKHPHALG_.add(index, value);
          onChanged();
        } else {
          unk3100IMPDKHPHALGBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Unk3100_MCIBDBBEKEK Unk3100_IMPDKHPHALG = 2;</code>
       */
      public Builder addUnk3100IMPDKHPHALG(
          emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEK.Builder builderForValue) {
        if (unk3100IMPDKHPHALGBuilder_ == null) {
          ensureUnk3100IMPDKHPHALGIsMutable();
          unk3100IMPDKHPHALG_.add(builderForValue.build());
          onChanged();
        } else {
          unk3100IMPDKHPHALGBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Unk3100_MCIBDBBEKEK Unk3100_IMPDKHPHALG = 2;</code>
       */
      public Builder addUnk3100IMPDKHPHALG(
          int index, emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEK.Builder builderForValue) {
        if (unk3100IMPDKHPHALGBuilder_ == null) {
          ensureUnk3100IMPDKHPHALGIsMutable();
          unk3100IMPDKHPHALG_.add(index, builderForValue.build());
          onChanged();
        } else {
          unk3100IMPDKHPHALGBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Unk3100_MCIBDBBEKEK Unk3100_IMPDKHPHALG = 2;</code>
       */
      public Builder addAllUnk3100IMPDKHPHALG(
          java.lang.Iterable<? extends emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEK> values) {
        if (unk3100IMPDKHPHALGBuilder_ == null) {
          ensureUnk3100IMPDKHPHALGIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, unk3100IMPDKHPHALG_);
          onChanged();
        } else {
          unk3100IMPDKHPHALGBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Unk3100_MCIBDBBEKEK Unk3100_IMPDKHPHALG = 2;</code>
       */
      public Builder clearUnk3100IMPDKHPHALG() {
        if (unk3100IMPDKHPHALGBuilder_ == null) {
          unk3100IMPDKHPHALG_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          unk3100IMPDKHPHALGBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Unk3100_MCIBDBBEKEK Unk3100_IMPDKHPHALG = 2;</code>
       */
      public Builder removeUnk3100IMPDKHPHALG(int index) {
        if (unk3100IMPDKHPHALGBuilder_ == null) {
          ensureUnk3100IMPDKHPHALGIsMutable();
          unk3100IMPDKHPHALG_.remove(index);
          onChanged();
        } else {
          unk3100IMPDKHPHALGBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Unk3100_MCIBDBBEKEK Unk3100_IMPDKHPHALG = 2;</code>
       */
      public emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEK.Builder getUnk3100IMPDKHPHALGBuilder(
          int index) {
        return getUnk3100IMPDKHPHALGFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Unk3100_MCIBDBBEKEK Unk3100_IMPDKHPHALG = 2;</code>
       */
      public emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEKOrBuilder getUnk3100IMPDKHPHALGOrBuilder(
          int index) {
        if (unk3100IMPDKHPHALGBuilder_ == null) {
          return unk3100IMPDKHPHALG_.get(index);  } else {
          return unk3100IMPDKHPHALGBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Unk3100_MCIBDBBEKEK Unk3100_IMPDKHPHALG = 2;</code>
       */
      public java.util.List<? extends emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEKOrBuilder> 
           getUnk3100IMPDKHPHALGOrBuilderList() {
        if (unk3100IMPDKHPHALGBuilder_ != null) {
          return unk3100IMPDKHPHALGBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(unk3100IMPDKHPHALG_);
        }
      }
      /**
       * <code>repeated .Unk3100_MCIBDBBEKEK Unk3100_IMPDKHPHALG = 2;</code>
       */
      public emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEK.Builder addUnk3100IMPDKHPHALGBuilder() {
        return getUnk3100IMPDKHPHALGFieldBuilder().addBuilder(
            emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEK.getDefaultInstance());
      }
      /**
       * <code>repeated .Unk3100_MCIBDBBEKEK Unk3100_IMPDKHPHALG = 2;</code>
       */
      public emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEK.Builder addUnk3100IMPDKHPHALGBuilder(
          int index) {
        return getUnk3100IMPDKHPHALGFieldBuilder().addBuilder(
            index, emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEK.getDefaultInstance());
      }
      /**
       * <code>repeated .Unk3100_MCIBDBBEKEK Unk3100_IMPDKHPHALG = 2;</code>
       */
      public java.util.List<emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEK.Builder> 
           getUnk3100IMPDKHPHALGBuilderList() {
        return getUnk3100IMPDKHPHALGFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEK, emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEK.Builder, emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEKOrBuilder> 
          getUnk3100IMPDKHPHALGFieldBuilder() {
        if (unk3100IMPDKHPHALGBuilder_ == null) {
          unk3100IMPDKHPHALGBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEK, emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEK.Builder, emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.Unk3100_MCIBDBBEKEKOrBuilder>(
                  unk3100IMPDKHPHALG_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          unk3100IMPDKHPHALG_ = null;
        }
        return unk3100IMPDKHPHALGBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Unk3100_FGDECIHNIJG)
    }

    // @@protoc_insertion_point(class_scope:Unk3100_FGDECIHNIJG)
    private static final emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG();
    }

    public static emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Unk3100_FGDECIHNIJG>
        PARSER = new com.google.protobuf.AbstractParser<Unk3100_FGDECIHNIJG>() {
      @java.lang.Override
      public Unk3100_FGDECIHNIJG parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Unk3100_FGDECIHNIJG(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Unk3100_FGDECIHNIJG> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Unk3100_FGDECIHNIJG> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public emu.grasscutter.net.proto.Unk3100FGDECIHNIJG.Unk3100_FGDECIHNIJG getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Unk3100_FGDECIHNIJG_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Unk3100_FGDECIHNIJG_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031Unk3100_FGDECIHNIJG.proto\032\031Unk3100_MCI" +
      "BDBBEKEK.proto\"H\n\023Unk3100_FGDECIHNIJG\0221\n" +
      "\023Unk3100_IMPDKHPHALG\030\002 \003(\0132\024.Unk3100_MCI" +
      "BDBBEKEKB\033\n\031emu.grasscutter.net.protob\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.getDescriptor(),
        });
    internal_static_Unk3100_FGDECIHNIJG_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Unk3100_FGDECIHNIJG_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Unk3100_FGDECIHNIJG_descriptor,
        new java.lang.String[] { "Unk3100IMPDKHPHALG", });
    emu.grasscutter.net.proto.Unk3100MCIBDBBEKEK.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
