// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Unk3100_AILMJOHBIDC.proto

package emu.grasscutter.net.proto;

public final class Unk3100AILMJOHBIDC {
  private Unk3100AILMJOHBIDC() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Unk3100_AILMJOHBIDCOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Unk3100_AILMJOHBIDC)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated uint32 Unk3100_KHPFAPCPGBE = 15;</code>
     * @return A list containing the unk3100KHPFAPCPGBE.
     */
    java.util.List<java.lang.Integer> getUnk3100KHPFAPCPGBEList();
    /**
     * <code>repeated uint32 Unk3100_KHPFAPCPGBE = 15;</code>
     * @return The count of unk3100KHPFAPCPGBE.
     */
    int getUnk3100KHPFAPCPGBECount();
    /**
     * <code>repeated uint32 Unk3100_KHPFAPCPGBE = 15;</code>
     * @param index The index of the element to return.
     * @return The unk3100KHPFAPCPGBE at the given index.
     */
    int getUnk3100KHPFAPCPGBE(int index);

    /**
     * <code>uint32 coin_c = 12;</code>
     * @return The coinC.
     */
    int getCoinC();

    /**
     * <code>uint32 Unk3100_BCHHFFJEJCD = 4;</code>
     * @return The unk3100BCHHFFJEJCD.
     */
    int getUnk3100BCHHFFJEJCD();
  }
  /**
   * <pre>
   * CmdId: 24201
   * EnetChannelId: 0
   * EnetIsReliable: true
   * </pre>
   *
   * Protobuf type {@code Unk3100_AILMJOHBIDC}
   */
  public static final class Unk3100_AILMJOHBIDC extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Unk3100_AILMJOHBIDC)
      Unk3100_AILMJOHBIDCOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Unk3100_AILMJOHBIDC.newBuilder() to construct.
    private Unk3100_AILMJOHBIDC(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Unk3100_AILMJOHBIDC() {
      unk3100KHPFAPCPGBE_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Unk3100_AILMJOHBIDC();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Unk3100_AILMJOHBIDC(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 32: {

              unk3100BCHHFFJEJCD_ = input.readUInt32();
              break;
            }
            case 96: {

              coinC_ = input.readUInt32();
              break;
            }
            case 120: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                unk3100KHPFAPCPGBE_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              unk3100KHPFAPCPGBE_.addInt(input.readUInt32());
              break;
            }
            case 122: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                unk3100KHPFAPCPGBE_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                unk3100KHPFAPCPGBE_.addInt(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          unk3100KHPFAPCPGBE_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.internal_static_Unk3100_AILMJOHBIDC_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.internal_static_Unk3100_AILMJOHBIDC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC.class, emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC.Builder.class);
    }

    public static final int UNK3100_KHPFAPCPGBE_FIELD_NUMBER = 15;
    private com.google.protobuf.Internal.IntList unk3100KHPFAPCPGBE_;
    /**
     * <code>repeated uint32 Unk3100_KHPFAPCPGBE = 15;</code>
     * @return A list containing the unk3100KHPFAPCPGBE.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getUnk3100KHPFAPCPGBEList() {
      return unk3100KHPFAPCPGBE_;
    }
    /**
     * <code>repeated uint32 Unk3100_KHPFAPCPGBE = 15;</code>
     * @return The count of unk3100KHPFAPCPGBE.
     */
    public int getUnk3100KHPFAPCPGBECount() {
      return unk3100KHPFAPCPGBE_.size();
    }
    /**
     * <code>repeated uint32 Unk3100_KHPFAPCPGBE = 15;</code>
     * @param index The index of the element to return.
     * @return The unk3100KHPFAPCPGBE at the given index.
     */
    public int getUnk3100KHPFAPCPGBE(int index) {
      return unk3100KHPFAPCPGBE_.getInt(index);
    }
    private int unk3100KHPFAPCPGBEMemoizedSerializedSize = -1;

    public static final int COIN_C_FIELD_NUMBER = 12;
    private int coinC_;
    /**
     * <code>uint32 coin_c = 12;</code>
     * @return The coinC.
     */
    @java.lang.Override
    public int getCoinC() {
      return coinC_;
    }

    public static final int UNK3100_BCHHFFJEJCD_FIELD_NUMBER = 4;
    private int unk3100BCHHFFJEJCD_;
    /**
     * <code>uint32 Unk3100_BCHHFFJEJCD = 4;</code>
     * @return The unk3100BCHHFFJEJCD.
     */
    @java.lang.Override
    public int getUnk3100BCHHFFJEJCD() {
      return unk3100BCHHFFJEJCD_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (unk3100BCHHFFJEJCD_ != 0) {
        output.writeUInt32(4, unk3100BCHHFFJEJCD_);
      }
      if (coinC_ != 0) {
        output.writeUInt32(12, coinC_);
      }
      if (getUnk3100KHPFAPCPGBEList().size() > 0) {
        output.writeUInt32NoTag(122);
        output.writeUInt32NoTag(unk3100KHPFAPCPGBEMemoizedSerializedSize);
      }
      for (int i = 0; i < unk3100KHPFAPCPGBE_.size(); i++) {
        output.writeUInt32NoTag(unk3100KHPFAPCPGBE_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (unk3100BCHHFFJEJCD_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, unk3100BCHHFFJEJCD_);
      }
      if (coinC_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(12, coinC_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < unk3100KHPFAPCPGBE_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(unk3100KHPFAPCPGBE_.getInt(i));
        }
        size += dataSize;
        if (!getUnk3100KHPFAPCPGBEList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        unk3100KHPFAPCPGBEMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC)) {
        return super.equals(obj);
      }
      emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC other = (emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC) obj;

      if (!getUnk3100KHPFAPCPGBEList()
          .equals(other.getUnk3100KHPFAPCPGBEList())) return false;
      if (getCoinC()
          != other.getCoinC()) return false;
      if (getUnk3100BCHHFFJEJCD()
          != other.getUnk3100BCHHFFJEJCD()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getUnk3100KHPFAPCPGBECount() > 0) {
        hash = (37 * hash) + UNK3100_KHPFAPCPGBE_FIELD_NUMBER;
        hash = (53 * hash) + getUnk3100KHPFAPCPGBEList().hashCode();
      }
      hash = (37 * hash) + COIN_C_FIELD_NUMBER;
      hash = (53 * hash) + getCoinC();
      hash = (37 * hash) + UNK3100_BCHHFFJEJCD_FIELD_NUMBER;
      hash = (53 * hash) + getUnk3100BCHHFFJEJCD();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * CmdId: 24201
     * EnetChannelId: 0
     * EnetIsReliable: true
     * </pre>
     *
     * Protobuf type {@code Unk3100_AILMJOHBIDC}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Unk3100_AILMJOHBIDC)
        emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDCOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.internal_static_Unk3100_AILMJOHBIDC_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.internal_static_Unk3100_AILMJOHBIDC_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC.class, emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC.Builder.class);
      }

      // Construct using emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        unk3100KHPFAPCPGBE_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        coinC_ = 0;

        unk3100BCHHFFJEJCD_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.internal_static_Unk3100_AILMJOHBIDC_descriptor;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC getDefaultInstanceForType() {
        return emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC.getDefaultInstance();
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC build() {
        emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC buildPartial() {
        emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC result = new emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          unk3100KHPFAPCPGBE_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.unk3100KHPFAPCPGBE_ = unk3100KHPFAPCPGBE_;
        result.coinC_ = coinC_;
        result.unk3100BCHHFFJEJCD_ = unk3100BCHHFFJEJCD_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC) {
          return mergeFrom((emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC other) {
        if (other == emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC.getDefaultInstance()) return this;
        if (!other.unk3100KHPFAPCPGBE_.isEmpty()) {
          if (unk3100KHPFAPCPGBE_.isEmpty()) {
            unk3100KHPFAPCPGBE_ = other.unk3100KHPFAPCPGBE_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUnk3100KHPFAPCPGBEIsMutable();
            unk3100KHPFAPCPGBE_.addAll(other.unk3100KHPFAPCPGBE_);
          }
          onChanged();
        }
        if (other.getCoinC() != 0) {
          setCoinC(other.getCoinC());
        }
        if (other.getUnk3100BCHHFFJEJCD() != 0) {
          setUnk3100BCHHFFJEJCD(other.getUnk3100BCHHFFJEJCD());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.IntList unk3100KHPFAPCPGBE_ = emptyIntList();
      private void ensureUnk3100KHPFAPCPGBEIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          unk3100KHPFAPCPGBE_ = mutableCopy(unk3100KHPFAPCPGBE_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated uint32 Unk3100_KHPFAPCPGBE = 15;</code>
       * @return A list containing the unk3100KHPFAPCPGBE.
       */
      public java.util.List<java.lang.Integer>
          getUnk3100KHPFAPCPGBEList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(unk3100KHPFAPCPGBE_) : unk3100KHPFAPCPGBE_;
      }
      /**
       * <code>repeated uint32 Unk3100_KHPFAPCPGBE = 15;</code>
       * @return The count of unk3100KHPFAPCPGBE.
       */
      public int getUnk3100KHPFAPCPGBECount() {
        return unk3100KHPFAPCPGBE_.size();
      }
      /**
       * <code>repeated uint32 Unk3100_KHPFAPCPGBE = 15;</code>
       * @param index The index of the element to return.
       * @return The unk3100KHPFAPCPGBE at the given index.
       */
      public int getUnk3100KHPFAPCPGBE(int index) {
        return unk3100KHPFAPCPGBE_.getInt(index);
      }
      /**
       * <code>repeated uint32 Unk3100_KHPFAPCPGBE = 15;</code>
       * @param index The index to set the value at.
       * @param value The unk3100KHPFAPCPGBE to set.
       * @return This builder for chaining.
       */
      public Builder setUnk3100KHPFAPCPGBE(
          int index, int value) {
        ensureUnk3100KHPFAPCPGBEIsMutable();
        unk3100KHPFAPCPGBE_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 Unk3100_KHPFAPCPGBE = 15;</code>
       * @param value The unk3100KHPFAPCPGBE to add.
       * @return This builder for chaining.
       */
      public Builder addUnk3100KHPFAPCPGBE(int value) {
        ensureUnk3100KHPFAPCPGBEIsMutable();
        unk3100KHPFAPCPGBE_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 Unk3100_KHPFAPCPGBE = 15;</code>
       * @param values The unk3100KHPFAPCPGBE to add.
       * @return This builder for chaining.
       */
      public Builder addAllUnk3100KHPFAPCPGBE(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureUnk3100KHPFAPCPGBEIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, unk3100KHPFAPCPGBE_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 Unk3100_KHPFAPCPGBE = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnk3100KHPFAPCPGBE() {
        unk3100KHPFAPCPGBE_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private int coinC_ ;
      /**
       * <code>uint32 coin_c = 12;</code>
       * @return The coinC.
       */
      @java.lang.Override
      public int getCoinC() {
        return coinC_;
      }
      /**
       * <code>uint32 coin_c = 12;</code>
       * @param value The coinC to set.
       * @return This builder for chaining.
       */
      public Builder setCoinC(int value) {
        
        coinC_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 coin_c = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearCoinC() {
        
        coinC_ = 0;
        onChanged();
        return this;
      }

      private int unk3100BCHHFFJEJCD_ ;
      /**
       * <code>uint32 Unk3100_BCHHFFJEJCD = 4;</code>
       * @return The unk3100BCHHFFJEJCD.
       */
      @java.lang.Override
      public int getUnk3100BCHHFFJEJCD() {
        return unk3100BCHHFFJEJCD_;
      }
      /**
       * <code>uint32 Unk3100_BCHHFFJEJCD = 4;</code>
       * @param value The unk3100BCHHFFJEJCD to set.
       * @return This builder for chaining.
       */
      public Builder setUnk3100BCHHFFJEJCD(int value) {
        
        unk3100BCHHFFJEJCD_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 Unk3100_BCHHFFJEJCD = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnk3100BCHHFFJEJCD() {
        
        unk3100BCHHFFJEJCD_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Unk3100_AILMJOHBIDC)
    }

    // @@protoc_insertion_point(class_scope:Unk3100_AILMJOHBIDC)
    private static final emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC();
    }

    public static emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Unk3100_AILMJOHBIDC>
        PARSER = new com.google.protobuf.AbstractParser<Unk3100_AILMJOHBIDC>() {
      @java.lang.Override
      public Unk3100_AILMJOHBIDC parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Unk3100_AILMJOHBIDC(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Unk3100_AILMJOHBIDC> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Unk3100_AILMJOHBIDC> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public emu.grasscutter.net.proto.Unk3100AILMJOHBIDC.Unk3100_AILMJOHBIDC getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Unk3100_AILMJOHBIDC_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Unk3100_AILMJOHBIDC_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031Unk3100_AILMJOHBIDC.proto\"_\n\023Unk3100_A" +
      "ILMJOHBIDC\022\033\n\023Unk3100_KHPFAPCPGBE\030\017 \003(\r\022" +
      "\016\n\006coin_c\030\014 \001(\r\022\033\n\023Unk3100_BCHHFFJEJCD\030\004" +
      " \001(\rB\033\n\031emu.grasscutter.net.protob\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Unk3100_AILMJOHBIDC_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Unk3100_AILMJOHBIDC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Unk3100_AILMJOHBIDC_descriptor,
        new java.lang.String[] { "Unk3100KHPFAPCPGBE", "CoinC", "Unk3100BCHHFFJEJCD", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
