// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Unk3100_APOOGGMHCJI.proto

package emu.grasscutter.net.proto;

public final class Unk3100APOOGGMHCJI {
  private Unk3100APOOGGMHCJI() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Unk3100_APOOGGMHCJIOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Unk3100_APOOGGMHCJI)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 Unk3100_LINPNGLHPDL = 10;</code>
     * @return The unk3100LINPNGLHPDL.
     */
    int getUnk3100LINPNGLHPDL();

    /**
     * <code>bool is_open = 11;</code>
     * @return The isOpen.
     */
    boolean getIsOpen();

    /**
     * <code>bool Unk2700_MMNILGLDHHD = 5;</code>
     * @return The unk2700MMNILGLDHHD.
     */
    boolean getUnk2700MMNILGLDHHD();

    /**
     * <code>uint32 stage_id = 1;</code>
     * @return The stageId.
     */
    int getStageId();
  }
  /**
   * Protobuf type {@code Unk3100_APOOGGMHCJI}
   */
  public static final class Unk3100_APOOGGMHCJI extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Unk3100_APOOGGMHCJI)
      Unk3100_APOOGGMHCJIOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Unk3100_APOOGGMHCJI.newBuilder() to construct.
    private Unk3100_APOOGGMHCJI(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Unk3100_APOOGGMHCJI() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Unk3100_APOOGGMHCJI();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Unk3100_APOOGGMHCJI(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              stageId_ = input.readUInt32();
              break;
            }
            case 40: {

              unk2700MMNILGLDHHD_ = input.readBool();
              break;
            }
            case 80: {

              unk3100LINPNGLHPDL_ = input.readUInt32();
              break;
            }
            case 88: {

              isOpen_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.internal_static_Unk3100_APOOGGMHCJI_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.internal_static_Unk3100_APOOGGMHCJI_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI.class, emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI.Builder.class);
    }

    public static final int UNK3100_LINPNGLHPDL_FIELD_NUMBER = 10;
    private int unk3100LINPNGLHPDL_;
    /**
     * <code>uint32 Unk3100_LINPNGLHPDL = 10;</code>
     * @return The unk3100LINPNGLHPDL.
     */
    @java.lang.Override
    public int getUnk3100LINPNGLHPDL() {
      return unk3100LINPNGLHPDL_;
    }

    public static final int IS_OPEN_FIELD_NUMBER = 11;
    private boolean isOpen_;
    /**
     * <code>bool is_open = 11;</code>
     * @return The isOpen.
     */
    @java.lang.Override
    public boolean getIsOpen() {
      return isOpen_;
    }

    public static final int UNK2700_MMNILGLDHHD_FIELD_NUMBER = 5;
    private boolean unk2700MMNILGLDHHD_;
    /**
     * <code>bool Unk2700_MMNILGLDHHD = 5;</code>
     * @return The unk2700MMNILGLDHHD.
     */
    @java.lang.Override
    public boolean getUnk2700MMNILGLDHHD() {
      return unk2700MMNILGLDHHD_;
    }

    public static final int STAGE_ID_FIELD_NUMBER = 1;
    private int stageId_;
    /**
     * <code>uint32 stage_id = 1;</code>
     * @return The stageId.
     */
    @java.lang.Override
    public int getStageId() {
      return stageId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (stageId_ != 0) {
        output.writeUInt32(1, stageId_);
      }
      if (unk2700MMNILGLDHHD_ != false) {
        output.writeBool(5, unk2700MMNILGLDHHD_);
      }
      if (unk3100LINPNGLHPDL_ != 0) {
        output.writeUInt32(10, unk3100LINPNGLHPDL_);
      }
      if (isOpen_ != false) {
        output.writeBool(11, isOpen_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (stageId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, stageId_);
      }
      if (unk2700MMNILGLDHHD_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, unk2700MMNILGLDHHD_);
      }
      if (unk3100LINPNGLHPDL_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(10, unk3100LINPNGLHPDL_);
      }
      if (isOpen_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(11, isOpen_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI)) {
        return super.equals(obj);
      }
      emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI other = (emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI) obj;

      if (getUnk3100LINPNGLHPDL()
          != other.getUnk3100LINPNGLHPDL()) return false;
      if (getIsOpen()
          != other.getIsOpen()) return false;
      if (getUnk2700MMNILGLDHHD()
          != other.getUnk2700MMNILGLDHHD()) return false;
      if (getStageId()
          != other.getStageId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UNK3100_LINPNGLHPDL_FIELD_NUMBER;
      hash = (53 * hash) + getUnk3100LINPNGLHPDL();
      hash = (37 * hash) + IS_OPEN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsOpen());
      hash = (37 * hash) + UNK2700_MMNILGLDHHD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getUnk2700MMNILGLDHHD());
      hash = (37 * hash) + STAGE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getStageId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Unk3100_APOOGGMHCJI}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Unk3100_APOOGGMHCJI)
        emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJIOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.internal_static_Unk3100_APOOGGMHCJI_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.internal_static_Unk3100_APOOGGMHCJI_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI.class, emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI.Builder.class);
      }

      // Construct using emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        unk3100LINPNGLHPDL_ = 0;

        isOpen_ = false;

        unk2700MMNILGLDHHD_ = false;

        stageId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.internal_static_Unk3100_APOOGGMHCJI_descriptor;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI getDefaultInstanceForType() {
        return emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI.getDefaultInstance();
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI build() {
        emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI buildPartial() {
        emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI result = new emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI(this);
        result.unk3100LINPNGLHPDL_ = unk3100LINPNGLHPDL_;
        result.isOpen_ = isOpen_;
        result.unk2700MMNILGLDHHD_ = unk2700MMNILGLDHHD_;
        result.stageId_ = stageId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI) {
          return mergeFrom((emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI other) {
        if (other == emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI.getDefaultInstance()) return this;
        if (other.getUnk3100LINPNGLHPDL() != 0) {
          setUnk3100LINPNGLHPDL(other.getUnk3100LINPNGLHPDL());
        }
        if (other.getIsOpen() != false) {
          setIsOpen(other.getIsOpen());
        }
        if (other.getUnk2700MMNILGLDHHD() != false) {
          setUnk2700MMNILGLDHHD(other.getUnk2700MMNILGLDHHD());
        }
        if (other.getStageId() != 0) {
          setStageId(other.getStageId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int unk3100LINPNGLHPDL_ ;
      /**
       * <code>uint32 Unk3100_LINPNGLHPDL = 10;</code>
       * @return The unk3100LINPNGLHPDL.
       */
      @java.lang.Override
      public int getUnk3100LINPNGLHPDL() {
        return unk3100LINPNGLHPDL_;
      }
      /**
       * <code>uint32 Unk3100_LINPNGLHPDL = 10;</code>
       * @param value The unk3100LINPNGLHPDL to set.
       * @return This builder for chaining.
       */
      public Builder setUnk3100LINPNGLHPDL(int value) {
        
        unk3100LINPNGLHPDL_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 Unk3100_LINPNGLHPDL = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnk3100LINPNGLHPDL() {
        
        unk3100LINPNGLHPDL_ = 0;
        onChanged();
        return this;
      }

      private boolean isOpen_ ;
      /**
       * <code>bool is_open = 11;</code>
       * @return The isOpen.
       */
      @java.lang.Override
      public boolean getIsOpen() {
        return isOpen_;
      }
      /**
       * <code>bool is_open = 11;</code>
       * @param value The isOpen to set.
       * @return This builder for chaining.
       */
      public Builder setIsOpen(boolean value) {
        
        isOpen_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_open = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsOpen() {
        
        isOpen_ = false;
        onChanged();
        return this;
      }

      private boolean unk2700MMNILGLDHHD_ ;
      /**
       * <code>bool Unk2700_MMNILGLDHHD = 5;</code>
       * @return The unk2700MMNILGLDHHD.
       */
      @java.lang.Override
      public boolean getUnk2700MMNILGLDHHD() {
        return unk2700MMNILGLDHHD_;
      }
      /**
       * <code>bool Unk2700_MMNILGLDHHD = 5;</code>
       * @param value The unk2700MMNILGLDHHD to set.
       * @return This builder for chaining.
       */
      public Builder setUnk2700MMNILGLDHHD(boolean value) {
        
        unk2700MMNILGLDHHD_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool Unk2700_MMNILGLDHHD = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnk2700MMNILGLDHHD() {
        
        unk2700MMNILGLDHHD_ = false;
        onChanged();
        return this;
      }

      private int stageId_ ;
      /**
       * <code>uint32 stage_id = 1;</code>
       * @return The stageId.
       */
      @java.lang.Override
      public int getStageId() {
        return stageId_;
      }
      /**
       * <code>uint32 stage_id = 1;</code>
       * @param value The stageId to set.
       * @return This builder for chaining.
       */
      public Builder setStageId(int value) {
        
        stageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 stage_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStageId() {
        
        stageId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Unk3100_APOOGGMHCJI)
    }

    // @@protoc_insertion_point(class_scope:Unk3100_APOOGGMHCJI)
    private static final emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI();
    }

    public static emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Unk3100_APOOGGMHCJI>
        PARSER = new com.google.protobuf.AbstractParser<Unk3100_APOOGGMHCJI>() {
      @java.lang.Override
      public Unk3100_APOOGGMHCJI parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Unk3100_APOOGGMHCJI(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Unk3100_APOOGGMHCJI> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Unk3100_APOOGGMHCJI> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public emu.grasscutter.net.proto.Unk3100APOOGGMHCJI.Unk3100_APOOGGMHCJI getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Unk3100_APOOGGMHCJI_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Unk3100_APOOGGMHCJI_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031Unk3100_APOOGGMHCJI.proto\"r\n\023Unk3100_A" +
      "POOGGMHCJI\022\033\n\023Unk3100_LINPNGLHPDL\030\n \001(\r\022" +
      "\017\n\007is_open\030\013 \001(\010\022\033\n\023Unk2700_MMNILGLDHHD\030" +
      "\005 \001(\010\022\020\n\010stage_id\030\001 \001(\rB\033\n\031emu.grasscutt" +
      "er.net.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Unk3100_APOOGGMHCJI_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Unk3100_APOOGGMHCJI_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Unk3100_APOOGGMHCJI_descriptor,
        new java.lang.String[] { "Unk3100LINPNGLHPDL", "IsOpen", "Unk2700MMNILGLDHHD", "StageId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
