// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Unk3100_IALGADDCFNN.proto

package emu.grasscutter.net.proto;

public final class Unk3100IALGADDCFNN {
  private Unk3100IALGADDCFNN() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Unk3100_IALGADDCFNNOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Unk3100_IALGADDCFNN)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated uint32 Unk3100_CKABCMCIPLM = 5;</code>
     * @return A list containing the unk3100CKABCMCIPLM.
     */
    java.util.List<java.lang.Integer> getUnk3100CKABCMCIPLMList();
    /**
     * <code>repeated uint32 Unk3100_CKABCMCIPLM = 5;</code>
     * @return The count of unk3100CKABCMCIPLM.
     */
    int getUnk3100CKABCMCIPLMCount();
    /**
     * <code>repeated uint32 Unk3100_CKABCMCIPLM = 5;</code>
     * @param index The index of the element to return.
     * @return The unk3100CKABCMCIPLM at the given index.
     */
    int getUnk3100CKABCMCIPLM(int index);

    /**
     * <code>repeated uint32 Unk3100_CJIAFHOLGPB = 14;</code>
     * @return A list containing the unk3100CJIAFHOLGPB.
     */
    java.util.List<java.lang.Integer> getUnk3100CJIAFHOLGPBList();
    /**
     * <code>repeated uint32 Unk3100_CJIAFHOLGPB = 14;</code>
     * @return The count of unk3100CJIAFHOLGPB.
     */
    int getUnk3100CJIAFHOLGPBCount();
    /**
     * <code>repeated uint32 Unk3100_CJIAFHOLGPB = 14;</code>
     * @param index The index of the element to return.
     * @return The unk3100CJIAFHOLGPB at the given index.
     */
    int getUnk3100CJIAFHOLGPB(int index);

    /**
     * <code>repeated uint32 Unk3100_CKOJIKGDEPO = 2;</code>
     * @return A list containing the unk3100CKOJIKGDEPO.
     */
    java.util.List<java.lang.Integer> getUnk3100CKOJIKGDEPOList();
    /**
     * <code>repeated uint32 Unk3100_CKOJIKGDEPO = 2;</code>
     * @return The count of unk3100CKOJIKGDEPO.
     */
    int getUnk3100CKOJIKGDEPOCount();
    /**
     * <code>repeated uint32 Unk3100_CKOJIKGDEPO = 2;</code>
     * @param index The index of the element to return.
     * @return The unk3100CKOJIKGDEPO at the given index.
     */
    int getUnk3100CKOJIKGDEPO(int index);

    /**
     * <code>uint32 Unk3100_MBDCDNHEDFO = 3;</code>
     * @return The unk3100MBDCDNHEDFO.
     */
    int getUnk3100MBDCDNHEDFO();

    /**
     * <code>uint32 Unk3100_CIJIHEGPEMB = 10;</code>
     * @return The unk3100CIJIHEGPEMB.
     */
    int getUnk3100CIJIHEGPEMB();
  }
  /**
   * Protobuf type {@code Unk3100_IALGADDCFNN}
   */
  public static final class Unk3100_IALGADDCFNN extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Unk3100_IALGADDCFNN)
      Unk3100_IALGADDCFNNOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Unk3100_IALGADDCFNN.newBuilder() to construct.
    private Unk3100_IALGADDCFNN(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Unk3100_IALGADDCFNN() {
      unk3100CKABCMCIPLM_ = emptyIntList();
      unk3100CJIAFHOLGPB_ = emptyIntList();
      unk3100CKOJIKGDEPO_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Unk3100_IALGADDCFNN();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Unk3100_IALGADDCFNN(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 16: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                unk3100CKOJIKGDEPO_ = newIntList();
                mutable_bitField0_ |= 0x00000004;
              }
              unk3100CKOJIKGDEPO_.addInt(input.readUInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) != 0) && input.getBytesUntilLimit() > 0) {
                unk3100CKOJIKGDEPO_ = newIntList();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                unk3100CKOJIKGDEPO_.addInt(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 24: {

              unk3100MBDCDNHEDFO_ = input.readUInt32();
              break;
            }
            case 40: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                unk3100CKABCMCIPLM_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              unk3100CKABCMCIPLM_.addInt(input.readUInt32());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                unk3100CKABCMCIPLM_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                unk3100CKABCMCIPLM_.addInt(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 80: {

              unk3100CIJIHEGPEMB_ = input.readUInt32();
              break;
            }
            case 112: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                unk3100CJIAFHOLGPB_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              unk3100CJIAFHOLGPB_.addInt(input.readUInt32());
              break;
            }
            case 114: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
                unk3100CJIAFHOLGPB_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                unk3100CJIAFHOLGPB_.addInt(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          unk3100CKOJIKGDEPO_.makeImmutable(); // C
        }
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          unk3100CKABCMCIPLM_.makeImmutable(); // C
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          unk3100CJIAFHOLGPB_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return emu.grasscutter.net.proto.Unk3100IALGADDCFNN.internal_static_Unk3100_IALGADDCFNN_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return emu.grasscutter.net.proto.Unk3100IALGADDCFNN.internal_static_Unk3100_IALGADDCFNN_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN.class, emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN.Builder.class);
    }

    public static final int UNK3100_CKABCMCIPLM_FIELD_NUMBER = 5;
    private com.google.protobuf.Internal.IntList unk3100CKABCMCIPLM_;
    /**
     * <code>repeated uint32 Unk3100_CKABCMCIPLM = 5;</code>
     * @return A list containing the unk3100CKABCMCIPLM.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getUnk3100CKABCMCIPLMList() {
      return unk3100CKABCMCIPLM_;
    }
    /**
     * <code>repeated uint32 Unk3100_CKABCMCIPLM = 5;</code>
     * @return The count of unk3100CKABCMCIPLM.
     */
    public int getUnk3100CKABCMCIPLMCount() {
      return unk3100CKABCMCIPLM_.size();
    }
    /**
     * <code>repeated uint32 Unk3100_CKABCMCIPLM = 5;</code>
     * @param index The index of the element to return.
     * @return The unk3100CKABCMCIPLM at the given index.
     */
    public int getUnk3100CKABCMCIPLM(int index) {
      return unk3100CKABCMCIPLM_.getInt(index);
    }
    private int unk3100CKABCMCIPLMMemoizedSerializedSize = -1;

    public static final int UNK3100_CJIAFHOLGPB_FIELD_NUMBER = 14;
    private com.google.protobuf.Internal.IntList unk3100CJIAFHOLGPB_;
    /**
     * <code>repeated uint32 Unk3100_CJIAFHOLGPB = 14;</code>
     * @return A list containing the unk3100CJIAFHOLGPB.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getUnk3100CJIAFHOLGPBList() {
      return unk3100CJIAFHOLGPB_;
    }
    /**
     * <code>repeated uint32 Unk3100_CJIAFHOLGPB = 14;</code>
     * @return The count of unk3100CJIAFHOLGPB.
     */
    public int getUnk3100CJIAFHOLGPBCount() {
      return unk3100CJIAFHOLGPB_.size();
    }
    /**
     * <code>repeated uint32 Unk3100_CJIAFHOLGPB = 14;</code>
     * @param index The index of the element to return.
     * @return The unk3100CJIAFHOLGPB at the given index.
     */
    public int getUnk3100CJIAFHOLGPB(int index) {
      return unk3100CJIAFHOLGPB_.getInt(index);
    }
    private int unk3100CJIAFHOLGPBMemoizedSerializedSize = -1;

    public static final int UNK3100_CKOJIKGDEPO_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.IntList unk3100CKOJIKGDEPO_;
    /**
     * <code>repeated uint32 Unk3100_CKOJIKGDEPO = 2;</code>
     * @return A list containing the unk3100CKOJIKGDEPO.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getUnk3100CKOJIKGDEPOList() {
      return unk3100CKOJIKGDEPO_;
    }
    /**
     * <code>repeated uint32 Unk3100_CKOJIKGDEPO = 2;</code>
     * @return The count of unk3100CKOJIKGDEPO.
     */
    public int getUnk3100CKOJIKGDEPOCount() {
      return unk3100CKOJIKGDEPO_.size();
    }
    /**
     * <code>repeated uint32 Unk3100_CKOJIKGDEPO = 2;</code>
     * @param index The index of the element to return.
     * @return The unk3100CKOJIKGDEPO at the given index.
     */
    public int getUnk3100CKOJIKGDEPO(int index) {
      return unk3100CKOJIKGDEPO_.getInt(index);
    }
    private int unk3100CKOJIKGDEPOMemoizedSerializedSize = -1;

    public static final int UNK3100_MBDCDNHEDFO_FIELD_NUMBER = 3;
    private int unk3100MBDCDNHEDFO_;
    /**
     * <code>uint32 Unk3100_MBDCDNHEDFO = 3;</code>
     * @return The unk3100MBDCDNHEDFO.
     */
    @java.lang.Override
    public int getUnk3100MBDCDNHEDFO() {
      return unk3100MBDCDNHEDFO_;
    }

    public static final int UNK3100_CIJIHEGPEMB_FIELD_NUMBER = 10;
    private int unk3100CIJIHEGPEMB_;
    /**
     * <code>uint32 Unk3100_CIJIHEGPEMB = 10;</code>
     * @return The unk3100CIJIHEGPEMB.
     */
    @java.lang.Override
    public int getUnk3100CIJIHEGPEMB() {
      return unk3100CIJIHEGPEMB_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getUnk3100CKOJIKGDEPOList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(unk3100CKOJIKGDEPOMemoizedSerializedSize);
      }
      for (int i = 0; i < unk3100CKOJIKGDEPO_.size(); i++) {
        output.writeUInt32NoTag(unk3100CKOJIKGDEPO_.getInt(i));
      }
      if (unk3100MBDCDNHEDFO_ != 0) {
        output.writeUInt32(3, unk3100MBDCDNHEDFO_);
      }
      if (getUnk3100CKABCMCIPLMList().size() > 0) {
        output.writeUInt32NoTag(42);
        output.writeUInt32NoTag(unk3100CKABCMCIPLMMemoizedSerializedSize);
      }
      for (int i = 0; i < unk3100CKABCMCIPLM_.size(); i++) {
        output.writeUInt32NoTag(unk3100CKABCMCIPLM_.getInt(i));
      }
      if (unk3100CIJIHEGPEMB_ != 0) {
        output.writeUInt32(10, unk3100CIJIHEGPEMB_);
      }
      if (getUnk3100CJIAFHOLGPBList().size() > 0) {
        output.writeUInt32NoTag(114);
        output.writeUInt32NoTag(unk3100CJIAFHOLGPBMemoizedSerializedSize);
      }
      for (int i = 0; i < unk3100CJIAFHOLGPB_.size(); i++) {
        output.writeUInt32NoTag(unk3100CJIAFHOLGPB_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < unk3100CKOJIKGDEPO_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(unk3100CKOJIKGDEPO_.getInt(i));
        }
        size += dataSize;
        if (!getUnk3100CKOJIKGDEPOList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        unk3100CKOJIKGDEPOMemoizedSerializedSize = dataSize;
      }
      if (unk3100MBDCDNHEDFO_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, unk3100MBDCDNHEDFO_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < unk3100CKABCMCIPLM_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(unk3100CKABCMCIPLM_.getInt(i));
        }
        size += dataSize;
        if (!getUnk3100CKABCMCIPLMList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        unk3100CKABCMCIPLMMemoizedSerializedSize = dataSize;
      }
      if (unk3100CIJIHEGPEMB_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(10, unk3100CIJIHEGPEMB_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < unk3100CJIAFHOLGPB_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(unk3100CJIAFHOLGPB_.getInt(i));
        }
        size += dataSize;
        if (!getUnk3100CJIAFHOLGPBList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        unk3100CJIAFHOLGPBMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN)) {
        return super.equals(obj);
      }
      emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN other = (emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN) obj;

      if (!getUnk3100CKABCMCIPLMList()
          .equals(other.getUnk3100CKABCMCIPLMList())) return false;
      if (!getUnk3100CJIAFHOLGPBList()
          .equals(other.getUnk3100CJIAFHOLGPBList())) return false;
      if (!getUnk3100CKOJIKGDEPOList()
          .equals(other.getUnk3100CKOJIKGDEPOList())) return false;
      if (getUnk3100MBDCDNHEDFO()
          != other.getUnk3100MBDCDNHEDFO()) return false;
      if (getUnk3100CIJIHEGPEMB()
          != other.getUnk3100CIJIHEGPEMB()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getUnk3100CKABCMCIPLMCount() > 0) {
        hash = (37 * hash) + UNK3100_CKABCMCIPLM_FIELD_NUMBER;
        hash = (53 * hash) + getUnk3100CKABCMCIPLMList().hashCode();
      }
      if (getUnk3100CJIAFHOLGPBCount() > 0) {
        hash = (37 * hash) + UNK3100_CJIAFHOLGPB_FIELD_NUMBER;
        hash = (53 * hash) + getUnk3100CJIAFHOLGPBList().hashCode();
      }
      if (getUnk3100CKOJIKGDEPOCount() > 0) {
        hash = (37 * hash) + UNK3100_CKOJIKGDEPO_FIELD_NUMBER;
        hash = (53 * hash) + getUnk3100CKOJIKGDEPOList().hashCode();
      }
      hash = (37 * hash) + UNK3100_MBDCDNHEDFO_FIELD_NUMBER;
      hash = (53 * hash) + getUnk3100MBDCDNHEDFO();
      hash = (37 * hash) + UNK3100_CIJIHEGPEMB_FIELD_NUMBER;
      hash = (53 * hash) + getUnk3100CIJIHEGPEMB();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Unk3100_IALGADDCFNN}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Unk3100_IALGADDCFNN)
        emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNNOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return emu.grasscutter.net.proto.Unk3100IALGADDCFNN.internal_static_Unk3100_IALGADDCFNN_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return emu.grasscutter.net.proto.Unk3100IALGADDCFNN.internal_static_Unk3100_IALGADDCFNN_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN.class, emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN.Builder.class);
      }

      // Construct using emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        unk3100CKABCMCIPLM_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        unk3100CJIAFHOLGPB_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        unk3100CKOJIKGDEPO_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000004);
        unk3100MBDCDNHEDFO_ = 0;

        unk3100CIJIHEGPEMB_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return emu.grasscutter.net.proto.Unk3100IALGADDCFNN.internal_static_Unk3100_IALGADDCFNN_descriptor;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN getDefaultInstanceForType() {
        return emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN.getDefaultInstance();
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN build() {
        emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN buildPartial() {
        emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN result = new emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          unk3100CKABCMCIPLM_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.unk3100CKABCMCIPLM_ = unk3100CKABCMCIPLM_;
        if (((bitField0_ & 0x00000002) != 0)) {
          unk3100CJIAFHOLGPB_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.unk3100CJIAFHOLGPB_ = unk3100CJIAFHOLGPB_;
        if (((bitField0_ & 0x00000004) != 0)) {
          unk3100CKOJIKGDEPO_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.unk3100CKOJIKGDEPO_ = unk3100CKOJIKGDEPO_;
        result.unk3100MBDCDNHEDFO_ = unk3100MBDCDNHEDFO_;
        result.unk3100CIJIHEGPEMB_ = unk3100CIJIHEGPEMB_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN) {
          return mergeFrom((emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN other) {
        if (other == emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN.getDefaultInstance()) return this;
        if (!other.unk3100CKABCMCIPLM_.isEmpty()) {
          if (unk3100CKABCMCIPLM_.isEmpty()) {
            unk3100CKABCMCIPLM_ = other.unk3100CKABCMCIPLM_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUnk3100CKABCMCIPLMIsMutable();
            unk3100CKABCMCIPLM_.addAll(other.unk3100CKABCMCIPLM_);
          }
          onChanged();
        }
        if (!other.unk3100CJIAFHOLGPB_.isEmpty()) {
          if (unk3100CJIAFHOLGPB_.isEmpty()) {
            unk3100CJIAFHOLGPB_ = other.unk3100CJIAFHOLGPB_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureUnk3100CJIAFHOLGPBIsMutable();
            unk3100CJIAFHOLGPB_.addAll(other.unk3100CJIAFHOLGPB_);
          }
          onChanged();
        }
        if (!other.unk3100CKOJIKGDEPO_.isEmpty()) {
          if (unk3100CKOJIKGDEPO_.isEmpty()) {
            unk3100CKOJIKGDEPO_ = other.unk3100CKOJIKGDEPO_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureUnk3100CKOJIKGDEPOIsMutable();
            unk3100CKOJIKGDEPO_.addAll(other.unk3100CKOJIKGDEPO_);
          }
          onChanged();
        }
        if (other.getUnk3100MBDCDNHEDFO() != 0) {
          setUnk3100MBDCDNHEDFO(other.getUnk3100MBDCDNHEDFO());
        }
        if (other.getUnk3100CIJIHEGPEMB() != 0) {
          setUnk3100CIJIHEGPEMB(other.getUnk3100CIJIHEGPEMB());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.IntList unk3100CKABCMCIPLM_ = emptyIntList();
      private void ensureUnk3100CKABCMCIPLMIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          unk3100CKABCMCIPLM_ = mutableCopy(unk3100CKABCMCIPLM_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated uint32 Unk3100_CKABCMCIPLM = 5;</code>
       * @return A list containing the unk3100CKABCMCIPLM.
       */
      public java.util.List<java.lang.Integer>
          getUnk3100CKABCMCIPLMList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(unk3100CKABCMCIPLM_) : unk3100CKABCMCIPLM_;
      }
      /**
       * <code>repeated uint32 Unk3100_CKABCMCIPLM = 5;</code>
       * @return The count of unk3100CKABCMCIPLM.
       */
      public int getUnk3100CKABCMCIPLMCount() {
        return unk3100CKABCMCIPLM_.size();
      }
      /**
       * <code>repeated uint32 Unk3100_CKABCMCIPLM = 5;</code>
       * @param index The index of the element to return.
       * @return The unk3100CKABCMCIPLM at the given index.
       */
      public int getUnk3100CKABCMCIPLM(int index) {
        return unk3100CKABCMCIPLM_.getInt(index);
      }
      /**
       * <code>repeated uint32 Unk3100_CKABCMCIPLM = 5;</code>
       * @param index The index to set the value at.
       * @param value The unk3100CKABCMCIPLM to set.
       * @return This builder for chaining.
       */
      public Builder setUnk3100CKABCMCIPLM(
          int index, int value) {
        ensureUnk3100CKABCMCIPLMIsMutable();
        unk3100CKABCMCIPLM_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 Unk3100_CKABCMCIPLM = 5;</code>
       * @param value The unk3100CKABCMCIPLM to add.
       * @return This builder for chaining.
       */
      public Builder addUnk3100CKABCMCIPLM(int value) {
        ensureUnk3100CKABCMCIPLMIsMutable();
        unk3100CKABCMCIPLM_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 Unk3100_CKABCMCIPLM = 5;</code>
       * @param values The unk3100CKABCMCIPLM to add.
       * @return This builder for chaining.
       */
      public Builder addAllUnk3100CKABCMCIPLM(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureUnk3100CKABCMCIPLMIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, unk3100CKABCMCIPLM_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 Unk3100_CKABCMCIPLM = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnk3100CKABCMCIPLM() {
        unk3100CKABCMCIPLM_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList unk3100CJIAFHOLGPB_ = emptyIntList();
      private void ensureUnk3100CJIAFHOLGPBIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          unk3100CJIAFHOLGPB_ = mutableCopy(unk3100CJIAFHOLGPB_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated uint32 Unk3100_CJIAFHOLGPB = 14;</code>
       * @return A list containing the unk3100CJIAFHOLGPB.
       */
      public java.util.List<java.lang.Integer>
          getUnk3100CJIAFHOLGPBList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(unk3100CJIAFHOLGPB_) : unk3100CJIAFHOLGPB_;
      }
      /**
       * <code>repeated uint32 Unk3100_CJIAFHOLGPB = 14;</code>
       * @return The count of unk3100CJIAFHOLGPB.
       */
      public int getUnk3100CJIAFHOLGPBCount() {
        return unk3100CJIAFHOLGPB_.size();
      }
      /**
       * <code>repeated uint32 Unk3100_CJIAFHOLGPB = 14;</code>
       * @param index The index of the element to return.
       * @return The unk3100CJIAFHOLGPB at the given index.
       */
      public int getUnk3100CJIAFHOLGPB(int index) {
        return unk3100CJIAFHOLGPB_.getInt(index);
      }
      /**
       * <code>repeated uint32 Unk3100_CJIAFHOLGPB = 14;</code>
       * @param index The index to set the value at.
       * @param value The unk3100CJIAFHOLGPB to set.
       * @return This builder for chaining.
       */
      public Builder setUnk3100CJIAFHOLGPB(
          int index, int value) {
        ensureUnk3100CJIAFHOLGPBIsMutable();
        unk3100CJIAFHOLGPB_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 Unk3100_CJIAFHOLGPB = 14;</code>
       * @param value The unk3100CJIAFHOLGPB to add.
       * @return This builder for chaining.
       */
      public Builder addUnk3100CJIAFHOLGPB(int value) {
        ensureUnk3100CJIAFHOLGPBIsMutable();
        unk3100CJIAFHOLGPB_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 Unk3100_CJIAFHOLGPB = 14;</code>
       * @param values The unk3100CJIAFHOLGPB to add.
       * @return This builder for chaining.
       */
      public Builder addAllUnk3100CJIAFHOLGPB(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureUnk3100CJIAFHOLGPBIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, unk3100CJIAFHOLGPB_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 Unk3100_CJIAFHOLGPB = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnk3100CJIAFHOLGPB() {
        unk3100CJIAFHOLGPB_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList unk3100CKOJIKGDEPO_ = emptyIntList();
      private void ensureUnk3100CKOJIKGDEPOIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          unk3100CKOJIKGDEPO_ = mutableCopy(unk3100CKOJIKGDEPO_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated uint32 Unk3100_CKOJIKGDEPO = 2;</code>
       * @return A list containing the unk3100CKOJIKGDEPO.
       */
      public java.util.List<java.lang.Integer>
          getUnk3100CKOJIKGDEPOList() {
        return ((bitField0_ & 0x00000004) != 0) ?
                 java.util.Collections.unmodifiableList(unk3100CKOJIKGDEPO_) : unk3100CKOJIKGDEPO_;
      }
      /**
       * <code>repeated uint32 Unk3100_CKOJIKGDEPO = 2;</code>
       * @return The count of unk3100CKOJIKGDEPO.
       */
      public int getUnk3100CKOJIKGDEPOCount() {
        return unk3100CKOJIKGDEPO_.size();
      }
      /**
       * <code>repeated uint32 Unk3100_CKOJIKGDEPO = 2;</code>
       * @param index The index of the element to return.
       * @return The unk3100CKOJIKGDEPO at the given index.
       */
      public int getUnk3100CKOJIKGDEPO(int index) {
        return unk3100CKOJIKGDEPO_.getInt(index);
      }
      /**
       * <code>repeated uint32 Unk3100_CKOJIKGDEPO = 2;</code>
       * @param index The index to set the value at.
       * @param value The unk3100CKOJIKGDEPO to set.
       * @return This builder for chaining.
       */
      public Builder setUnk3100CKOJIKGDEPO(
          int index, int value) {
        ensureUnk3100CKOJIKGDEPOIsMutable();
        unk3100CKOJIKGDEPO_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 Unk3100_CKOJIKGDEPO = 2;</code>
       * @param value The unk3100CKOJIKGDEPO to add.
       * @return This builder for chaining.
       */
      public Builder addUnk3100CKOJIKGDEPO(int value) {
        ensureUnk3100CKOJIKGDEPOIsMutable();
        unk3100CKOJIKGDEPO_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 Unk3100_CKOJIKGDEPO = 2;</code>
       * @param values The unk3100CKOJIKGDEPO to add.
       * @return This builder for chaining.
       */
      public Builder addAllUnk3100CKOJIKGDEPO(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureUnk3100CKOJIKGDEPOIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, unk3100CKOJIKGDEPO_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 Unk3100_CKOJIKGDEPO = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnk3100CKOJIKGDEPO() {
        unk3100CKOJIKGDEPO_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private int unk3100MBDCDNHEDFO_ ;
      /**
       * <code>uint32 Unk3100_MBDCDNHEDFO = 3;</code>
       * @return The unk3100MBDCDNHEDFO.
       */
      @java.lang.Override
      public int getUnk3100MBDCDNHEDFO() {
        return unk3100MBDCDNHEDFO_;
      }
      /**
       * <code>uint32 Unk3100_MBDCDNHEDFO = 3;</code>
       * @param value The unk3100MBDCDNHEDFO to set.
       * @return This builder for chaining.
       */
      public Builder setUnk3100MBDCDNHEDFO(int value) {
        
        unk3100MBDCDNHEDFO_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 Unk3100_MBDCDNHEDFO = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnk3100MBDCDNHEDFO() {
        
        unk3100MBDCDNHEDFO_ = 0;
        onChanged();
        return this;
      }

      private int unk3100CIJIHEGPEMB_ ;
      /**
       * <code>uint32 Unk3100_CIJIHEGPEMB = 10;</code>
       * @return The unk3100CIJIHEGPEMB.
       */
      @java.lang.Override
      public int getUnk3100CIJIHEGPEMB() {
        return unk3100CIJIHEGPEMB_;
      }
      /**
       * <code>uint32 Unk3100_CIJIHEGPEMB = 10;</code>
       * @param value The unk3100CIJIHEGPEMB to set.
       * @return This builder for chaining.
       */
      public Builder setUnk3100CIJIHEGPEMB(int value) {
        
        unk3100CIJIHEGPEMB_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 Unk3100_CIJIHEGPEMB = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnk3100CIJIHEGPEMB() {
        
        unk3100CIJIHEGPEMB_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Unk3100_IALGADDCFNN)
    }

    // @@protoc_insertion_point(class_scope:Unk3100_IALGADDCFNN)
    private static final emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN();
    }

    public static emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Unk3100_IALGADDCFNN>
        PARSER = new com.google.protobuf.AbstractParser<Unk3100_IALGADDCFNN>() {
      @java.lang.Override
      public Unk3100_IALGADDCFNN parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Unk3100_IALGADDCFNN(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Unk3100_IALGADDCFNN> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Unk3100_IALGADDCFNN> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public emu.grasscutter.net.proto.Unk3100IALGADDCFNN.Unk3100_IALGADDCFNN getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Unk3100_IALGADDCFNN_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Unk3100_IALGADDCFNN_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031Unk3100_IALGADDCFNN.proto\"\246\001\n\023Unk3100_" +
      "IALGADDCFNN\022\033\n\023Unk3100_CKABCMCIPLM\030\005 \003(\r" +
      "\022\033\n\023Unk3100_CJIAFHOLGPB\030\016 \003(\r\022\033\n\023Unk3100" +
      "_CKOJIKGDEPO\030\002 \003(\r\022\033\n\023Unk3100_MBDCDNHEDF" +
      "O\030\003 \001(\r\022\033\n\023Unk3100_CIJIHEGPEMB\030\n \001(\rB\033\n\031" +
      "emu.grasscutter.net.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Unk3100_IALGADDCFNN_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Unk3100_IALGADDCFNN_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Unk3100_IALGADDCFNN_descriptor,
        new java.lang.String[] { "Unk3100CKABCMCIPLM", "Unk3100CJIAFHOLGPB", "Unk3100CKOJIKGDEPO", "Unk3100MBDCDNHEDFO", "Unk3100CIJIHEGPEMB", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
