// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Unk3100_FMAINCNFHOL.proto

package emu.grasscutter.net.proto;

public final class Unk3100FMAINCNFHOL {
  private Unk3100FMAINCNFHOL() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Unk3100_FMAINCNFHOLOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Unk3100_FMAINCNFHOL)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 retcode = 6;</code>
     * @return The retcode.
     */
    int getRetcode();

    /**
     * <code>uint32 Unk3100_FOOACIGDBFB = 3;</code>
     * @return The unk3100FOOACIGDBFB.
     */
    int getUnk3100FOOACIGDBFB();
  }
  /**
   * <pre>
   * CmdId: 22181
   * EnetChannelId: 0
   * EnetIsReliable: true
   * </pre>
   *
   * Protobuf type {@code Unk3100_FMAINCNFHOL}
   */
  public static final class Unk3100_FMAINCNFHOL extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Unk3100_FMAINCNFHOL)
      Unk3100_FMAINCNFHOLOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Unk3100_FMAINCNFHOL.newBuilder() to construct.
    private Unk3100_FMAINCNFHOL(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Unk3100_FMAINCNFHOL() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Unk3100_FMAINCNFHOL();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Unk3100_FMAINCNFHOL(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 24: {

              unk3100FOOACIGDBFB_ = input.readUInt32();
              break;
            }
            case 48: {

              retcode_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.internal_static_Unk3100_FMAINCNFHOL_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.internal_static_Unk3100_FMAINCNFHOL_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL.class, emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL.Builder.class);
    }

    public static final int RETCODE_FIELD_NUMBER = 6;
    private int retcode_;
    /**
     * <code>int32 retcode = 6;</code>
     * @return The retcode.
     */
    @java.lang.Override
    public int getRetcode() {
      return retcode_;
    }

    public static final int UNK3100_FOOACIGDBFB_FIELD_NUMBER = 3;
    private int unk3100FOOACIGDBFB_;
    /**
     * <code>uint32 Unk3100_FOOACIGDBFB = 3;</code>
     * @return The unk3100FOOACIGDBFB.
     */
    @java.lang.Override
    public int getUnk3100FOOACIGDBFB() {
      return unk3100FOOACIGDBFB_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (unk3100FOOACIGDBFB_ != 0) {
        output.writeUInt32(3, unk3100FOOACIGDBFB_);
      }
      if (retcode_ != 0) {
        output.writeInt32(6, retcode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (unk3100FOOACIGDBFB_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, unk3100FOOACIGDBFB_);
      }
      if (retcode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, retcode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL)) {
        return super.equals(obj);
      }
      emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL other = (emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL) obj;

      if (getRetcode()
          != other.getRetcode()) return false;
      if (getUnk3100FOOACIGDBFB()
          != other.getUnk3100FOOACIGDBFB()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RETCODE_FIELD_NUMBER;
      hash = (53 * hash) + getRetcode();
      hash = (37 * hash) + UNK3100_FOOACIGDBFB_FIELD_NUMBER;
      hash = (53 * hash) + getUnk3100FOOACIGDBFB();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * CmdId: 22181
     * EnetChannelId: 0
     * EnetIsReliable: true
     * </pre>
     *
     * Protobuf type {@code Unk3100_FMAINCNFHOL}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Unk3100_FMAINCNFHOL)
        emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOLOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.internal_static_Unk3100_FMAINCNFHOL_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.internal_static_Unk3100_FMAINCNFHOL_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL.class, emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL.Builder.class);
      }

      // Construct using emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        retcode_ = 0;

        unk3100FOOACIGDBFB_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.internal_static_Unk3100_FMAINCNFHOL_descriptor;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL getDefaultInstanceForType() {
        return emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL.getDefaultInstance();
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL build() {
        emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL buildPartial() {
        emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL result = new emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL(this);
        result.retcode_ = retcode_;
        result.unk3100FOOACIGDBFB_ = unk3100FOOACIGDBFB_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL) {
          return mergeFrom((emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL other) {
        if (other == emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL.getDefaultInstance()) return this;
        if (other.getRetcode() != 0) {
          setRetcode(other.getRetcode());
        }
        if (other.getUnk3100FOOACIGDBFB() != 0) {
          setUnk3100FOOACIGDBFB(other.getUnk3100FOOACIGDBFB());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int retcode_ ;
      /**
       * <code>int32 retcode = 6;</code>
       * @return The retcode.
       */
      @java.lang.Override
      public int getRetcode() {
        return retcode_;
      }
      /**
       * <code>int32 retcode = 6;</code>
       * @param value The retcode to set.
       * @return This builder for chaining.
       */
      public Builder setRetcode(int value) {
        
        retcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 retcode = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearRetcode() {
        
        retcode_ = 0;
        onChanged();
        return this;
      }

      private int unk3100FOOACIGDBFB_ ;
      /**
       * <code>uint32 Unk3100_FOOACIGDBFB = 3;</code>
       * @return The unk3100FOOACIGDBFB.
       */
      @java.lang.Override
      public int getUnk3100FOOACIGDBFB() {
        return unk3100FOOACIGDBFB_;
      }
      /**
       * <code>uint32 Unk3100_FOOACIGDBFB = 3;</code>
       * @param value The unk3100FOOACIGDBFB to set.
       * @return This builder for chaining.
       */
      public Builder setUnk3100FOOACIGDBFB(int value) {
        
        unk3100FOOACIGDBFB_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 Unk3100_FOOACIGDBFB = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnk3100FOOACIGDBFB() {
        
        unk3100FOOACIGDBFB_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Unk3100_FMAINCNFHOL)
    }

    // @@protoc_insertion_point(class_scope:Unk3100_FMAINCNFHOL)
    private static final emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL();
    }

    public static emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Unk3100_FMAINCNFHOL>
        PARSER = new com.google.protobuf.AbstractParser<Unk3100_FMAINCNFHOL>() {
      @java.lang.Override
      public Unk3100_FMAINCNFHOL parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Unk3100_FMAINCNFHOL(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Unk3100_FMAINCNFHOL> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Unk3100_FMAINCNFHOL> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public emu.grasscutter.net.proto.Unk3100FMAINCNFHOL.Unk3100_FMAINCNFHOL getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Unk3100_FMAINCNFHOL_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Unk3100_FMAINCNFHOL_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031Unk3100_FMAINCNFHOL.proto\"C\n\023Unk3100_F" +
      "MAINCNFHOL\022\017\n\007retcode\030\006 \001(\005\022\033\n\023Unk3100_F" +
      "OOACIGDBFB\030\003 \001(\rB\033\n\031emu.grasscutter.net." +
      "protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Unk3100_FMAINCNFHOL_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Unk3100_FMAINCNFHOL_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Unk3100_FMAINCNFHOL_descriptor,
        new java.lang.String[] { "Retcode", "Unk3100FOOACIGDBFB", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
